const pairs = [
{ key:"hei", value:" hi"},
{ key:"hallo", value:" hello"},
{ key:"velkommen", value:" welcome "},
{ key:"takk", value:" thanks "},
{ key:"at", value:" that, which "},
{ key:"å", value:" to"},
{ key:"om", value:" about, in, if "},
{ key:"omtrent", value:" around "},
{ key:"den/det", value:" that "},
{ key:"denne/dette", value:" this "},
{ key:"disse", value:" these "},
{ key:"de", value:" those "},
{ key:"har", value:"have "},
{ key:"hadde", value:" had"},
{ key:"takk for sist", value:" goodsee you again"},
{ key:"går", value:"go, walk"},
{ key:"gått", value:" gone "},
{ key:"drå", value:" go"},
{ key:"dro", value:" went, left"},
{ key:"gikk", value:" went"},
{ key:"da", value:" then"},
{ key:"da", value:" when "},
{ key:"beklager", value:" sorry "},
{ key:"unnskyld", value:" excuse me, sorry"},
{ key:"en unnskyldning/unnskyldningen", value:"excuse, apology"},
{ key:"veldig", value:" very "},
{ key:"mye", value:" much, a lot"},
{ key:"mange", value:" many, a lot "},
{ key:"flere", value:" several"},
{ key:"hvor", value:" where, how "},
{ key:"hva", value:" what "},
{ key:"hva enn", value:" whatever, that which"},
{ key:"hvilke/hvilket/hvilken", value:" which"},
{ key:"hvem", value:" who "},
{ key:"hvem sin/hvem sitt/hvem sine", value:" whoose "},
{ key:"hvor mye", value:" how much"},
{ key:"hvor mange", value:" how many"},
{ key:"hvor gammel", value:" how old"},
{ key:"hvordan", value:" how"},
{ key:"hvorfor", value:" why"},
{ key:"hver/hvert", value:" every, each "},
{ key:"hvis", value:" if"},
{ key:"når", value:" when "},
{ key:"koster", value:"cost"},
{ key:"kostet", value:" cost "},
{ key:"heter", value:" are called "},
{ key:"het", value:" was called"},
{ key:"her", value:" here"},
{ key:"hitt", value:" here"},
{ key:"der", value:" there "},
{ key:"mer", value:" more"},
{ key:"med", value:" with "},
{ key:"men", value:" but"},
{ key:"ikke", value:" not "},
{ key:"også", value:" also"},
{ key:"morsom/morsomme ", value:" funny "},
{ key:"gøy", value:" fun "},
{ key:"bare", value:" only"},
{ key:"bare hyggelig", value:" youre welcome "},
{ key:"hyggelig", value:" pleasant, pleasure, nice "},
{ key:"vær så snill", value:" please "},
{ key:"vær så god", value:" here you go"},
{ key:"vær", value:"be"},
{ key:"var", value:" was"},
{ key:"kanskje", value:" maybe"},
{ key:"en helg/helgen", value:"weekend "},
{ key:"god/godt/gode", value:" good "},
{ key:"bedre", value:" better "},
{ key:"best", value:" best "},
{ key:"enn", value:" than "},
{ key:"en ost/osten", value:"cheese"},
{ key:"en fisk/fisken/fisker/fiskene ", value:"fish"},
{ key:"en mat/maten", value:"food"},
{ key:"lager/å lage", value:"make"},
{ key:"lager mat", value:"make food, cook"},
{ key:"laget", value:" made"},
{ key:"et lag/laget", value:"team"},
{ key:"en gitar/gitaren/gitarer/gitarene ", value:"guitar"},
{ key:"spiller/å spille ", value:"play "},
{ key:"spilte", value:" played"},
{ key:"et spill/spillet ", value:"game "},
{ key:"hører/å hore", value:"hear, listen "},
{ key:"høres", value:" sounds "},
{ key:"hørt", value:" heard "},
{ key:"hørte", value:" heard "},
{ key:"lytter/å lytte", value:"listen "},
{ key:"en lyd/lyden/lyder/lydene ", value:" sound"},
{ key:"en regning/regningen/regninger/regningene ", value:"bill, account"},
{ key:"en servitør/servitøren/servitører/servitørene ", value:"waiter "},
{ key:"ser/å se", value:"see "},
{ key:"ser ut", value:" looks, dukem "},
{ key:"ser frem", value:" look forwards"},
{ key:"så", value:" saw "},
{ key:"så frem", value:" was looking forwards"},
{ key:"sett", value:" seen "},
{ key:"en lege/legen/leger/legene ", value:"doctor "},
{ key:"en tannlege/tannlegen/tannleger/tannlegene ", value:"dentist"},
{ key:"et marked/markedet ", value:"market"},
{ key:"en professor/professoren ", value:"professor"},
{ key:"syk/sykt", value:" sick "},
{ key:"sjukt", value:" sickness"},
{ key:"en sykepleier/sykepleieren ", value:"nurse"},
{ key:"et sykehus/sykehuset ", value:"hospital"},
{ key:"en pille/pillen ", value:"pill"},
{ key:"snill/snillt/snille ", value:" kind, nice "},
{ key:"snillere", value:" kinder"},
{ key:"snillest", value:"kindest"},
{ key:"smart", value:" smart"},
{ key:"stressende", value:" stressful"},
{ key:"stress", value:"stress "},
{ key:"stress", value:"stress"},
{ key:"stresset", value:" stressed"},
{ key:"vanskelig/vanskelige ", value:" difficult"},
{ key:"lett", value:" easy, light "},
{ key:"lettere", value:" easier"},
{ key:"interessant", value:" interesting"},
{ key:"en jobb/jobben", value:"job"},
{ key:"jobber/å jobbe", value:"work "},
{ key:"jobbet", value:" worked"},
{ key:"varm/varmt", value:" warm"},
{ key:"varmere", value:" warmer, hotter"},
{ key:"kalt", value:" cold"},
{ key:"høy/høyt/høye", value:" tall "},
{ key:"høyt", value:" highly, loudly"},
{ key:"høyere", value:" higher, taller"},
{ key:"høyest", value:" highest, loudest"},
{ key:"høyre", value:" right "},
{ key:"venstre", value:" left "},
{ key:"drikker/å drikke ", value:"drink, drinking "},
{ key:"drikken", value:"drink "},
{ key:"drakk", value:" drank"},
{ key:"vannen", value:" water "},
{ key:"et vann/vannet", value:"water "},
{ key:"et egg/egget/egger/eggene ", value:"egg"},
{ key:"en kafe/kaféen", value:"cafeshop"},
{ key:"en kaffe/kaffen ", value:"coffee drink"},
{ key:"kaffemaskiner", value:"coffee machine"},
{ key:"melken", value:"milk "},
{ key:"et øl/ølet", value:"beer"},
{ key:"stor/stort/store ", value:" big "},
{ key:"større", value:" bigger "},
{ key:"størst", value:"biggest "},
{ key:"små", value:" small"},
{ key:"lite", value:" small "},
{ key:"litt", value:" a little "},
{ key:"litten", value:" little "},
{ key:"billig/billige", value:" cheap "},
{ key:"billiger/billigere ", value:" cheaper "},
{ key:"billigst", value:"cheapest"},
{ key:"dyr/dyrt/dyre", value:" expensive "},
{ key:"dyrere", value:" more expensive"},
{ key:"dyrest", value:" most expensive"},
{ key:"et dyr/dyret/dyr/dyrene ", value:"animal"},
{ key:"ofte", value:" often"},
{ key:"oftere", value:" more often"},
{ key:"aldri", value:" never "},
{ key:"av og til", value:" sometimes"},
{ key:"og", value:" and"},
{ key:"eller", value:" or"},
{ key:"borte", value:" away, gone "},
{ key:"lang/lange/langt", value:" far, long "},
{ key:"Norge", value:" Norway"},
{ key:"norsk", value:" norwegian "},
{ key:"Sverige", value:" Sweden"},
{ key:"fra", value:" from "},
{ key:"kommer", value:"come"},
{ key:"kom", value:" came "},
{ key:"kommet", value:" come "},
{ key:"kommer til", value:" going"},
{ key:"svømmer/å svømme ", value:"swim"},
{ key:"svømmet", value:" swam "},
{ key:"svømte", value:" swam "},
{ key:"svømt", value:" swam "},
{ key:"bor/å bo", value:"live, stay "},
{ key:"bodd", value:" lived "},
{ key:"bodde", value:" lived "},
{ key:"vet/å vite", value:"know"},
{ key:"visst", value:" known "},
{ key:"visste", value:" knew "},
{ key:"skriver/å skrive ", value:"write"},
{ key:"skrev", value:" wrote "},
{ key:"skrevet", value:" wrote "},
{ key:"skrivere", value:"printers"},
{ key:"leser/å lese", value:"read"},
{ key:"leste", value:" read "},
{ key:"lest", value:" read "},
{ key:"lærer/å lære", value:"learn "},
{ key:"en lærer/læreren ", value:"teacher "},
{ key:"snakker/å snakke ", value:"speak "},
{ key:"snakket", value:" spoke "},
{ key:"et språk/språket/språker/språkene ", value:"language"},
{ key:"forstår/å forstå ", value:"understand "},
{ key:"forstod", value:" understood"},
{ key:"et land/landet/land ", value:"country"},
{ key:"en landsby/landsbyen ", value:"village"},
{ key:"en by/byen", value:"city"},
{ key:"en te/teen", value:"tea"},
{ key:"en katt/katten/katter/kattene ", value:"cat"},
{ key:"en hund/hunden/hunder/hundene ", value:"dog"},
{ key:"et brød/brødet", value:"bread"},
{ key:"en bror/broren/brødre/brødrene ", value:"brother"},
{ key:"en mor/moren/mødre/mødre ", value:"mother "},
{ key:"en far/faren/fedre/fedrene ", value:"father "},
{ key:"en sønn/sønnen/sønner/sønnene ", value:"son "},
{ key:"en søster/søsteren/søstre/søstrene ", value:"sister "},
{ key:"et søsken/søskenet/søskner/søsknene ", value:"sibling "},
{ key:"en datter/datteren/døtre/døtrene ", value:"daughter "},
{ key:"en gutt/gutten/gutter/guttene ", value:"boy"},
{ key:"en kvinne/kvinnen/kvinner/kvinnene ", value:"woman"},
{ key:"kvinneklær", value:" woman clothing"},
{ key:"en man/mannen/menn/mennen ", value:"man, husband "},
{ key:"man", value:" you (one)"},
{ key:"en kone/konnen/koner/konnene ", value:"wife"},
{ key:"en jente/jenta/jenter/jentene ", value:"girl "},
{ key:"hvordan går det ", value:" how goes it"},
{ key:"det går bra", value:" it goes well"},
{ key:"går det bra?", value:" goes it well"},
{ key:"det", value:" that "},
{ key:"god morgen", value:" good morning"},
{ key:"god dag", value:" good afternoon"},
{ key:"god kveld", value:" good evening"},
{ key:"en morgen/morgenen/morgener/morgenene ", value:"morning"},
{ key:"morgnen", value:" morgnings"},
{ key:"morgningen", value:"morning"},
{ key:"en kveld/kvelden/kvelder/kveldene ", value:"evening"},
{ key:"jeg", value:" I "},
{ key:"du", value:" you"},
{ key:"han", value:" he"},
{ key:"hun", value:" she"},
{ key:"vi", value:" we"},
{ key:"dere", value:" you"},
{ key:"de", value:" they"},
{ key:"meg", value:" me "},
{ key:"har på seg", value:" is wearing "},
{ key:"deg", value:" you "},
{ key:"seg", value:" itself "},
{ key:"ham", value:" him "},
{ key:"henne", value:" her "},
{ key:"dem", value:" them"},
{ key:"deres", value:" yours, theirs"},
{ key:"oss", value:" us"},
{ key:"min/mine/mitt", value:" mine"},
{ key:"din/dine/dit", value:" yours"},
{ key:"hans", value:" his"},
{ key:"hennes", value:" hers"},
{ key:"sin/sitt/sine", value:" own's "},
{ key:"vår/vårt/våre", value:" our "},
{ key:"én/ett", value:" one"},
{ key:"to", value:" two"},
{ key:"tre", value:" three"},
{ key:"fire", value:" four"},
{ key:"fem", value:" five"},
{ key:"seks", value:" six"},
{ key:"sju", value:" seven"},
{ key:"åtte", value:" eight"},
{ key:"ni", value:" nine"},
{ key:"ti", value:" ten"},
{ key:"elleve", value:" eleven"},
{ key:"tolv", value:" twelve"},
{ key:"tretten", value:" thirteen"},
{ key:"fjorten", value:" fourteen"},
{ key:"femten", value:" fifteen"},
{ key:"seksten", value:" sixteen"},
{ key:"sytten", value:" seventeen"},
{ key:"atten", value:" eighteen"},
{ key:"nitten", value:" nineteen"},
{ key:"tjue", value:" twenty "},
{ key:"tretti", value:" thirty"},
{ key:"forti", value:" fourty"},
{ key:"femti", value:" fifty"},
{ key:"seksti", value:" sixty"},
{ key:"sytti", value:" seventy"},
{ key:"atti", value:" eighty"},
{ key:"nitti", value:" ninety"},
{ key:"hundre", value:" hundred "},
{ key:"tusen", value:" thousand"},
{ key:"tjueen", value:" twentyone"},
{ key:"tjueto", value:" twentytwo"},
{ key:"tjuetre", value:" twentythree"},
{ key:"tjuefire", value:" twentyfour"},
{ key:"fjuefem", value:" twentyfive"},
{ key:"tjueseks", value:" twentysix"},
{ key:"tjuesju", value:" twentyseven"},
{ key:"tjueåtte", value:" twentyeight"},
{ key:"tjueni", value:" twentynine"},
{ key:"første/først", value:" first"},
{ key:"andre", value:" second, other people"},
{ key:"den andre", value:"other"},
{ key:"tredje", value:" third"},
{ key:"fjerde", value:" fourth"},
{ key:"femte", value:" fifth"},
{ key:"sjette", value:" sixth"},
{ key:"sjuende", value:" seventh"},
{ key:"åttende", value:" eighth"},
{ key:"niende", value:" ninth"},
{ key:"tiende", value:" tenth"},
{ key:"ellevte", value:" eleventh"},
{ key:"tolvte", value:" twelvth"},
{ key:"trettende", value:" thirteenth"},
{ key:"fjortende", value:" fourteenth"},
{ key:"femtende", value:" fifteenth"},
{ key:"sekstende", value:" sixteenth"},
{ key:"syttende", value:" seventeenth"},
{ key:"attende", value:" eightteenth"},
{ key:"nittende", value:" nineteenth"},
{ key:"mandag", value:" Monday"},
{ key:"tirsdag", value:" Tuesday"},
{ key:"onsdag", value:" Wednessday"},
{ key:"torsdag", value:" Thursday"},
{ key:"fredag", value:" Friday"},
{ key:"lørdag", value:" Saturday"},
{ key:"sondag", value:" Sunday"},
{ key:"lørdagen", value:"Saturday "},
{ key:"på mandager", value:" mondays"},
{ key:"et morsmål/morsmålet ", value:"mothertongue"},
{ key:"en stasjon/stajonen ", value:"station"},
{ key:"et bibliotek/biblioteket ", value:"biblioteke"},
{ key:"en park/parken/parker/parkene ", value:"park"},
{ key:"en kirk/kirken/kirker/kirkene ", value:"church"},
{ key:"et hotell/hotellet/hoteller/hotellene ", value:"hotel"},
{ key:"et hotellromm/hotellrommet ", value:"hotel room"},
{ key:"et museum/museet/museer/museene ", value:"museum"},
{ key:"en meny/menyen", value:"menu"},
{ key:"en venn/vennen/venner/vennene ", value:"friend"},
{ key:"vennlig/vennlige ", value:" friendly "},
{ key:"en matbutikk/matbutikken ", value:"grocery store"},
{ key:"en butikk/butikken/butikker/butikkene ", value:"store"},
{ key:"en kino/kinoen", value:"cinema"},
{ key:"et apotek/apoteket ", value:"pharmacy"},
{ key:"et bakeri/bakeriet ", value:"bakery"},
{ key:"baker/å bake", value:"bake"},
{ key:"baker", value:" a baker"},
{ key:"ung/ungt/unge", value:" young "},
{ key:"unge", value:"young "},
{ key:"yngre", value:" younger"},
{ key:"gammel/gammelt/gamle ", value:" old "},
{ key:"eldre", value:" older"},
{ key:"ny/nye/nytt", value:" new"},
{ key:"nyere", value:" newer"},
{ key:"en minibank/minibanken ", value:"ATM"},
{ key:"en bank/banken", value:"bank "},
{ key:"journalist", value:" a journalist"},
{ key:"en advokat/advokaten/advokater/advokatene ", value:" a lawyer"},
{ key:"et universitet/universetetet ", value:"university"},
{ key:"januar", value:" January"},
{ key:"februar", value:" February"},
{ key:"mars", value:" Mars"},
{ key:"april", value:" April"},
{ key:"mai", value:" May"},
{ key:"juni", value:" June"},
{ key:"juli", value:" July"},
{ key:"august", value:" August"},
{ key:"september", value:" September"},
{ key:"oktober", value:" Oktober"},
{ key:"november", value:" November"},
{ key:"desember", value:" December"},
{ key:"et år/året/år/årene ", value:"year "},
{ key:"årets", value:" ofyear"},
{ key:"en uke/uken/uker ", value:"week"},
{ key:"en måned/måneden/måneder/månedene ", value:"month "},
{ key:"en banan/bananen/bananer/bananene ", value:"bannana"},
{ key:"et eple/eplet/epler/eplene", value:"apple"},
{ key:"en salat/salaten/?/salatene ", value:"salad, letuce"},
{ key:"i", value:" in "},
{ key:"i en time", value:" for an hour "},
{ key:"inn/inne", value:" inside "},
{ key:"ut/ute", value:" outside "},
{ key:"utenfor", value:" outside, outside of "},
{ key:"uten", value:" without "},
{ key:"på", value:" at, on "},
{ key:"til", value:" to, of "},
{ key:"i Norge", value:" in Norway"},
{ key:"i dag", value:" today"},
{ key:"i går", value:" dje, yesterday "},
{ key:"i forgårs", value:" pardje, day before yesterday"},
{ key:"i morges", value:" this morning"},
{ key:"i morgen", value:" nesër, tomorrow"},
{ key:"i overmorgen", value:" day after tomorrow"},
{ key:"i år", value:" this year"},
{ key:"i nærheten", value:" nearby "},
{ key:"nær/nærme", value:" near "},
{ key:"nærmest", value:" nearest"},
{ key:"en tid/tiden", value:"time "},
{ key:"gjør/å gjøre", value:"do "},
{ key:"gjort", value:" done "},
{ key:"gjorde", value:" did "},
{ key:"hos", value:" at, with "},
{ key:"møter/å møte", value:"meet "},
{ key:"et møte/møtet/møter ", value:"meeting"},
{ key:"møtte", value:" met "},
{ key:"møtt", value:" have met "},
{ key:"mot", value:" to, towards, against "},
{ key:"kan", value:" can "},
{ key:"står/å stå", value:"stand, stay "},
{ key:"stod", value:" stood"},
{ key:"bli", value:"stay,become "},
{ key:"ble", value:" was"},
{ key:"blitt", value:" been "},
{ key:"en gate/gaten/gater/gatene/gata ", value:"street "},
{ key:"skrike/å skrike ", value:"yell"},
{ key:"et skrik/skriket ", value:"scream"},
{ key:"halv", value:" half "},
{ key:"halvparted", value:" half of"},
{ key:"kvart", value:" quarter"},
{ key:"prater/å prate", value:"talk, chat "},
{ key:"pratet", value:" talked "},
{ key:"en prate/praten ", value:"chat"},
{ key:"glemmer/å glem", value:"forget "},
{ key:"glemt", value:" forgotten"},
{ key:"glemte", value:" forgot"},
{ key:"husker/å huske", value:"remember"},
{ key:"husket", value:" remembered "},
{ key:"prøv", value:"try"},
{ key:"prøvde", value:" tried"},
{ key:"en kjekse/kjeksen/kjeks/kjeksene ", value:"cookie, biskote"},
{ key:"et kjæledyr/kjæledyret/kjæledyrer/kjæledyrene ", value:"pet "},
{ key:"kjære", value:" dear "},
{ key:"en kjæreste/kjæresten ", value:"sweetheart, boyfriend, girlfriend"},
{ key:"kjærlighet", value:"love"},
{ key:"kjekke", value:" handsome"},
{ key:"kjedelige", value:" boring "},
{ key:"et kjøkken/kjøkkenet/kjøkkener/kjøkkenene ", value:"kitchen"},
{ key:"en kjole/kjolen/kjoler/kjolene ", value:"dress"},
{ key:"et kjøleskap/kjøleskapet/kjøleskaper/kjøleskapene ", value:"refrigerator"},
{ key:"kjøle", value:" cool"},
{ key:"et skape/skapet/skaper/skapene ", value:" closet"},
{ key:"kjøpe/å kjøpe", value:"buy "},
{ key:"et kjøpesenter/kjøpesenteret ", value:"shopping center, mall"},
{ key:"kjøpte", value:" bought "},
{ key:"kjører/å kjøre", value:"drive "},
{ key:"kjørte", value:" drove"},
{ key:"et kjøtt/kjøttet ", value:"meat "},
{ key:"klær/klæren/klærne ", value:" clothes "},
{ key:"en klesbutikk/klesbutikken/klesbutikker/klesbutikkene ", value:"clothing store"},
{ key:"kler", value:"get dressed "},
{ key:"kledd", value:" dressed, clothed"},
{ key:"kjempe", value:" giant"},
{ key:"kjempefint", value:" terrific"},
{ key:"kjempetungt", value:" really heavy "},
{ key:"kjempestor", value:" really big"},
{ key:"kjempevarmt", value:" really warm"},
{ key:"kjenner/å kjenne ", value:"know "},
{ key:"kjent/kjente", value:" known "},
{ key:"ukjent", value:" unknown"},
{ key:"et kjed/kjedet", value:"chain, necklace"},
{ key:"en krefte/kreften/kreftene ", value:"force, craft, power"},
{ key:"et uhell/uhellet ", value:"accident "},
{ key:"en ulykke/ulykken ", value:"accident"},
{ key:"kødder du", value:" are you f*cking"},
{ key:"hele/helt", value:" whole, totally, completely "},
{ key:"sikker/sikkert/sikre ", value:" surely"},
{ key:"forsiktig/forsiktige ", value:" careful"},
{ key:"neste", value:" next "},
{ key:"nesten", value:" almost "},
{ key:"det eneste", value:"only thing"},
{ key:"seg selv", value:" them selves"},
{ key:"holder/å holde", value:" hold, keep "},
{ key:"alt", value:" everything "},
{ key:"alle", value:" all, everybody "},
{ key:"altså", value:" so, therefore"},
{ key:"spiser/å spise", value:"eat"},
{ key:"spiste", value:" ate "},
{ key:"spist", value:" eaten "},
{ key:"så", value:" so, therefore "},
{ key:"må", value:" must, have"},
{ key:"måtte", value:" had to"},
{ key:"jo", value:" oncontrary "},
{ key:"faen", value:" f*ck "},
{ key:"dårlig/darlige", value:" bad "},
{ key:"verste", value:" worst "},
{ key:"fattig", value:" poor"},
{ key:"rik", value:" rich"},
{ key:"titte", value:" peek, check out"},
{ key:"tur", value:" turn, walk "},
{ key:"en tur/turen/turer/turene ", value:"trip "},
{ key:"fjelltur", value:" mountain hike"},
{ key:"teltur", value:" camping trip"},
{ key:"til a handle", value:"act"},
{ key:"elsker", value:"love "},
{ key:"får/å få", value:"get "},
{ key:"fått", value:" got"},
{ key:"fikk", value:" got "},
{ key:"forresten", value:" byway"},
{ key:"som", value:" like, which "},
{ key:"brenner", value:" burns"},
{ key:"skjer/å skje", value:"happen"},
{ key:"skjedde", value:" happened "},
{ key:"skjedd", value:" happened "},
{ key:"hjemme", value:" at home "},
{ key:"et hjem/hjemmet ", value:"home "},
{ key:"en nyhet/nyheten/nyheter/nyhetene ", value:"news "},
{ key:"en avis/avisen/aviser/avisene ", value:" newspaper "},
{ key:"nå", value:" now"},
{ key:"sen/sent", value:" late "},
{ key:"senere", value:" later"},
{ key:"av", value:" of "},
{ key:"tror", value:" believe "},
{ key:"en drit/dritten ", value:" shit"},
{ key:"selvfølgelig", value:" surely "},
{ key:"fortsatt", value:" still"},
{ key:"fortsetter", value:"continue"},
{ key:"fortsatte", value:" continued "},
{ key:"ennå", value:" yet "},
{ key:"fort", value:" fast, quickly "},
{ key:"rask/raskt/raske ", value:" fast"},
{ key:"raskest", value:"fastest"},
{ key:"sann/sant/sanne ", value:" true "},
{ key:"evige", value:" eternal"},
{ key:"en ild/ilden/ilder/ildene ", value:" fire "},
{ key:"bryter/å bryte", value:"break, switch "},
{ key:"brukket", value:" broken"},
{ key:"mens", value:" while"},
{ key:"makt", value:" power "},
{ key:"finne", value:" find"},
{ key:"fant", value:" found "},
{ key:"funnet", value:" found "},
{ key:"en forelder/forelderen/foreldre/foreldrene ", value:"parent"},
{ key:"en besteforelder/besteforelderen/besteforelderene ", value:"grandparent"},
{ key:"en bursdag/bursdagen/bursdager/bursdagene ", value:"birthday"},
{ key:"et burgsdagskort/bursdagskortet/bursdagskorter/bursdagskortene ", value:"birthday card"},
{ key:"en dag/dagen/dager/dagene ", value:"day "},
{ key:"en natt/natten/netter/nettene ", value:"night "},
{ key:"midnatt", value:" midnight "},
{ key:"redd/redde", value:" afraid "},
{ key:"egentlig", value:" really, actually "},
{ key:"virkelig", value:" really, truly"},
{ key:"siden", value:" since, ago "},
{ key:"losningen", value:"solution"},
{ key:"en frokost/frokosten ", value:"breakfast "},
{ key:"en lunsj/lunsjen ", value:"lunch"},
{ key:"en middag/middagen/middager/midaggene ", value:"dinner"},
{ key:"kveldsmat", value:" supper"},
{ key:"sier/å si", value:"say "},
{ key:"sa", value:" said "},
{ key:"sagt", value:" said "},
{ key:"si ifra", value:" let me know"},
{ key:"ifra", value:" from"},
{ key:"tenker/å tenke", value:"think"},
{ key:"tenkte", value:" thought"},
{ key:"gjerne", value:" like, gladly "},
{ key:"vil", value:"want "},
{ key:"ville", value:" wanted"},
{ key:"skal", value:" shall, will, going"},
{ key:"skulle", value:" would "},
{ key:"burde", value:" should "},
{ key:"en skjorte/skjorten/skjorter ", value:"shirt "},
{ key:"et skjørt/skjørtet ", value:"skirt"},
{ key:"en sko/skoen/sko/skoene ", value:"shoe"},
{ key:"joggerskoen", value:"sneakers"},
{ key:"en genser/genseren/genserne ", value:"sweater"},
{ key:"et intervju/intervjuet ", value:"interview "},
{ key:"tar/å ta", value:"take, catch "},
{ key:"tar med", value:"bring"},
{ key:"tar på", value:" touch"},
{ key:"tatt", value:" taken, cought "},
{ key:"i det hele tatt ", value:" at all"},
{ key:"tok", value:" took "},
{ key:"tok med", value:" brought"},
{ key:"stede", value:" place "},
{ key:"stedet", value:" instead "},
{ key:"skylle/å skylle ", value:"rinse, flush"},
{ key:"ned", value:" down "},
{ key:"første", value:" first"},
{ key:"en gang/gangen/ganger/gangene ", value:"time "},
{ key:"noen gang", value:" any time "},
{ key:"en time/timen/timer/timene ", value:"hour "},
{ key:"en gang/gangen/ganger/gangene", value:"hallway"},
{ key:"time", value:"appointment"},
{ key:"noe", value:" something"},
{ key:"noen", value:" some, any "},
{ key:"noens", value:" somebody's"},
{ key:"ingenting", value:" nothing "},
{ key:"ingen", value:" noone "},
{ key:"en ting/tingen/tinger/tingene ", value:"thing "},
{ key:"varet", value:"weather"},
{ key:"sol", value:" me diell, sunny "},
{ key:"en sol/solen", value:"sun"},
{ key:"regner", value:"rain "},
{ key:"snør", value:"snow "},
{ key:"snøen", value:"snow "},
{ key:"overskyet", value:" me re, cloudy "},
{ key:"en vår/våren", value:"spring "},
{ key:"en sommer/sommeren ", value:"summer"},
{ key:"en høst/høsten ", value:"fall, autumn"},
{ key:"en vinter/vinteren ", value:"winter"},
{ key:"kald/kaldt/kaldene ", value:" cold "},
{ key:"varm/vamrt/varme ", value:" hot "},
{ key:"synger/å synge", value:"sing"},
{ key:"en sang/sangen/sanger/sangene ", value:"song"},
{ key:"et kor/koret", value:"choir"},
{ key:"alltid", value:" always"},
{ key:"jogger/å jogge", value:"jog"},
{ key:"en hånd/hånden", value:"hand "},
{ key:"fots", value:" foot "},
{ key:"fotball", value:" futboll "},
{ key:"en kamp/kampen/kamper/kampene ", value:"match, game, fight, battle"},
{ key:"fotballkampen", value:"football match"},
{ key:"en ball/ballen", value:"ball"},
{ key:"liker/å like", value:"like, enjoy"},
{ key:"likte", value:" liked "},
{ key:"likt", value:" liked "},
{ key:"en seng/sengen", value:"bed "},
{ key:"et toalett/toalettet/toaletter/toalettene ", value:"restroom"},
{ key:"et bad/badet", value:"bath, bathroom "},
{ key:"bader/å bade", value:"bathe"},
{ key:"baderommet", value:"bathroom"},
{ key:"en badedrakte/badetrakten ", value:"swimsuit"},
{ key:"ren/rent/rene", value:" clean "},
{ key:"en restaurant/restauranten/restauranter ", value:"restaurant"},
{ key:"en romkamerat/romkameraten/romkamerater ", value:"roommate"},
{ key:"et soverom/soverommet ", value:"bedroom"},
{ key:"sover/å sove", value:"sleep, is sleeping "},
{ key:"sov", value:" slept "},
{ key:"sovet", value:" slept "},
{ key:"sovner", value:"fall asleep"},
{ key:"sovnet", value:" fell asleep"},
{ key:"trøtt", value:" tired"},
{ key:"sliten/slitne", value:" tired "},
{ key:"en billett/billeten/billeter/billetene ", value:"ticket "},
{ key:"et tog/toget", value:"train "},
{ key:"bestiller/å bestille ", value:"order"},
{ key:"avbestiller/å avbestille ", value:"cancel"},
{ key:"en bestilling/bestillingen ", value:"order"},
{ key:"betaler/å betale ", value:"pay "},
{ key:"kontant", value:" cash "},
{ key:"en kort/korten/kort ", value:" card, credit card"},
{ key:"en kredittkort/kredittkorten ", value:"credit card"},
{ key:"appen", value:"application "},
{ key:"en minutt/minutten/minutter/minuttene ", value:"minute"},
{ key:"klokka", value:" time (clock)"},
{ key:"tid", value:" time "},
{ key:"et bord/bordet/bord/bordene ", value:"table"},
{ key:"et skrivebord/skrivebordet ", value:"desk"},
{ key:"en leilighet/leiligheten/leiligheter ", value:"apartment"},
{ key:"et hus/huset/hus/husene ", value:"house"},
{ key:"en stol/stolen", value:"chair"},
{ key:"et set/setet", value:"seat"},
{ key:"stygg/stygt/stygge ", value:" ugly "},
{ key:"for", value:" too much, a lot "},
{ key:"for tiden", value:" currently, at this time"},
{ key:"på tide", value:" time"},
{ key:"vakker/vakkert/vakre ", value:" beautiful "},
{ key:"nettopp", value:" exactly, just "},
{ key:"flott/flotte", value:" great "},
{ key:"fin/fint/fine", value:" nice "},
{ key:"en størrelse/størrelsen/størrelser/størrelsene ", value:"(clothes) size"},
{ key:"leter", value:"look, looking"},
{ key:"etter", value:" for, after "},
{ key:"etterpå", value:" afterwards "},
{ key:"åpen/åpent/åpne ", value:" open "},
{ key:"åpner/å åpne", value:"open "},
{ key:"åpnet", value:" opened"},
{ key:"trenger/å trenge ", value:"need"},
{ key:"trengte", value:" needed"},
{ key:"finner/å finne", value:"find"},
{ key:"fant", value:" found"},
{ key:"finner sted", value:"take place"},
{ key:"fant sted", value:" took place"},
{ key:"en avgang/avgangen ", value:"departure"},
{ key:"en onkel/onkelen/onkeler/onkelene ", value:"uncle"},
{ key:"fantastisk", value:" fantastic"},
{ key:"en hylle/hyllen ", value:"shelf"},
{ key:"et teppe/teppet ", value:"carpet"},
{ key:"et teppe/teppet ", value:"blanket"},
{ key:"blir/å bli", value:"become "},
{ key:"blir du med", value:" are you comming along, will you become"},
{ key:"ledig", value:" free, available"},
{ key:"forsinket", value:" delayed"},
{ key:"bestefar/farfar/farmor ", value:" grandfather"},
{ key:"bestemor/mormor/morfar ", value:" grandmother"},
{ key:"søt/søtt/søtte", value:" sweet"},
{ key:"søtere", value:" sweeter"},
{ key:"søtest", value:"sweetest"},
{ key:"sukker", value:" sugar"},
{ key:"rett", value:" straight"},
{ key:"frem", value:" ahead "},
{ key:"en dyrehage/dyrehagen ", value:"zoo"},
{ key:"en elv/elven/elver/elvene/elva ", value:"river"},
{ key:"besøker/å besøke ", value:"visit "},
{ key:"en besøk/besøken/besøk/besøkene ", value:"visitor "},
{ key:"besøkt", value:" visited "},
{ key:"besøkte", value:" visited "},
{ key:"sentrum", value:" center "},
{ key:"sulten/sultent/sultne ", value:" hungry "},
{ key:"tørst/tørste", value:" thirsty "},
{ key:"en buss/bussen/busser/bussene ", value:"bus"},
{ key:"bussholdeplassen ", value:"bus stop"},
{ key:"bussbilleten", value:"bus ticket"},
{ key:"busstasjonnen", value:"bus station"},
{ key:"penger/pengene", value:"money "},
{ key:"et nummer/nummeret/numre/numrene ", value:"number"},
{ key:"en taxi/taxien ", value:"taxi"},
{ key:"en taxitur/taxituren ", value:"taxiride"},
{ key:"en adress/adressen/adresser/adressene ", value:"adress"},
{ key:"gjentar/å gjenta ", value:"repeat "},
{ key:"deler/å dele", value:"split, divide, share "},
{ key:"en del/delen/deler/delene ", value:"piece"},
{ key:"en familie/familien/familier/familiene ", value:"family"},
{ key:"en supp/suppen/supper/suppene ", value:"soup"},
{ key:"nervøs", value:" nervous"},
{ key:"et hode/hodet/hoder/hodene ", value:"head"},
{ key:"vond/vondt", value:" hurt, pain "},
{ key:"trist/triste", value:" sad"},
{ key:"glad/glade", value:" happy "},
{ key:"mindre", value:" less, smaller "},
{ key:"minste", value:" smallest, least "},
{ key:"minst", value:" at least "},
{ key:"i hvert fall", value:" at least, in any case"},
{ key:"smaker/å smake", value:"taste, tastes"},
{ key:"et håp/håpet", value:"hope"},
{ key:"håper/å håpe", value:"hope "},
{ key:"forhåpentligvis ", value:" hopefully"},
{ key:"et glass/glass/glassene ", value:"glass"},
{ key:"en fest/festen", value:"party"},
{ key:"fester/å feste", value:"party"},
{ key:"festet", value:" partied"},
{ key:"en brus/brusen", value:"soda"},
{ key:"en invitasjon/invitasjonen/invitasjoner/invitasjonene ", value:"invitation"},
{ key:"rodvinen", value:"read wine"},
{ key:"hjemme", value:" home "},
{ key:"hurra", value:" urra, horay, hooray"},
{ key:"et band/bandet", value:"band"},
{ key:"en ballong/ballongen ", value:"balloon"},
{ key:"en klov/klovnen ", value:"clown"},
{ key:"en gjest/gjesten/gjester/gjestene ", value:"guest"},
{ key:"en gave/gaven", value:"gift"},
{ key:"lar/å la", value:"let "},
{ key:"danser/å danse", value:"dance "},
{ key:"danset", value:" danced"},
{ key:"feirer/å feire", value:"celebrate "},
{ key:"en musik/musiken ", value:"music "},
{ key:"et navn/navnet/navn/navnene ", value:"name "},
{ key:"et fornavn/fornavnet ", value:"first name"},
{ key:"et etternavn/etternavnet ", value:"last name"},
{ key:"bedring", value:" recovery "},
{ key:"en feber/feberen/feber/feberne ", value:" fever"},
{ key:"frisk", value:" healthy"},
{ key:"lenger", value:" anymore "},
{ key:"lenge", value:" long "},
{ key:"en festival/festivalen ", value:"festival"},
{ key:"starter/å starte/start ", value:"start, initiate, launch "},
{ key:"startet", value:" started"},
{ key:"begynner/å begynne ", value:"begin"},
{ key:"begynte", value:" began"},
{ key:"slutter/å slutte ", value:"end, stop, quit"},
{ key:"en slutt/slutten ", value:"end"},
{ key:"avslutter/å avslutte ", value:"finish"},
{ key:"til slutt", value:" finally"},
{ key:"studerer/å studere ", value:"study"},
{ key:"drar/å dra", value:"go, leave "},
{ key:"en skog/skogen", value:"forest"},
{ key:"en skogkatt/skogkatten ", value:"forest cat"},
{ key:"dessverre", value:" unfortunately"},
{ key:"allerede", value:" already"},
{ key:"en lyst/lysten/lyster/lystene ", value:"desire "},
{ key:"lys/lyst", value:" bright, light "},
{ key:"et lys/lyset", value:"light"},
{ key:"lyse", value:"light"},
{ key:"en plan/planen/planer/planene ", value:"plan"},
{ key:"et instrument/instrumentet/instrumenter ", value:"instrument"},
{ key:"videospill", value:" videogame"},
{ key:"podkast/podcaster ", value:" podcast"},
{ key:"en grill/grillen ", value:"grill"},
{ key:"griller/å grille ", value:"grill"},
{ key:"grillet", value:" grilled"},
{ key:"en grillfeste/grillfesten ", value:"barbequeue"},
{ key:"en piano/pianoen ", value:"piano"},
{ key:"skitten", value:" dirty"},
{ key:"en baby/babyen", value:"baby"},
{ key:"et barn/barnet/barn/barna ", value:"child "},
{ key:"et barnebarn/barnebarnet/barnebarn/barnebarna ", value:"grandchild"},
{ key:"en historie/historien/historier/historiene ", value:"history"},
{ key:"fransk", value:" french"},
{ key:"amerikansk/amerikanske ", value:" american "},
{ key:"svensk", value:" swedish"},
{ key:"en student/studenten/studenter/studentene ", value:"student"},
{ key:"en fiolin/fiolinen ", value:"violin"},
{ key:"en hobby/hobbyen/hobbyer ", value:"hobby"},
{ key:"tennis", value:" tennis"},
{ key:"et pariserhjul/pariserhjulet ", value:"ferris wheel"},
{ key:"tidlig", value:" early "},
{ key:"tidligere", value:" earlier"},
{ key:"pommes fritesen ", value:"fried potatoes, french fries"},
{ key:"trener", value:"train, exercise "},
{ key:"en kopp/koppen/kopper/koppene ", value:"cup"},
{ key:"en yoghurt/yoghurten ", value:"yogurt"},
{ key:"frokostblanding ", value:" cereal"},
{ key:"en ris/risen", value:"rice"},
{ key:"en is/isen", value:"icecream"},
{ key:"en kylling/kyllingen/kyllinger/kyllingene ", value:"chicken"},
{ key:"en hage/hagen", value:"garden"},
{ key:"alene", value:" alone "},
{ key:"sammen", value:" together "},
{ key:"en trapp/trappen", value:"staircase, stairs"},
{ key:"et kollektiv/kollektivet ", value:"shared apartment"},
{ key:"et leilighetsbygg/leilighetsbygget ", value:"apartment building"},
{ key:"hvit/hvitt/hvite ", value:" white "},
{ key:"svart/svarte", value:" black "},
{ key:"rød/rødt/røde", value:" red "},
{ key:"grønn/grønt/grønne ", value:" green "},
{ key:"lilla", value:" purple"},
{ key:"oransje", value:" orange color"},
{ key:"gul/gult/gule", value:" yellow "},
{ key:"grå/grått/grå", value:" gray "},
{ key:"blå/blått/blå", value:" blue "},
{ key:"lyseblå", value:" light blue"},
{ key:"rosa", value:" pink"},
{ key:"brun/brunt/brune", value:" brown"},
{ key:"en grønnsak/grønnsaken/grønnsaker/grønnsakene ", value:"vegetable"},
{ key:"en nabo/naboen", value:"neighbor"},
{ key:"et nabolag/nabolaget ", value:"neighborhood"},
{ key:"skit/skitne", value:" dirty "},
{ key:"stille", value:" quiet"},
{ key:"stillere", value:" quieter"},
{ key:"foretrekker", value:" prefer"},
{ key:"en vase/vasen", value:"vase"},
{ key:"en blomst/blomsten/blomster/blomstene ", value:"flower"},
{ key:"en boke/boken/bøker/bøkene ", value:"book (easy search boken) (boka si -- her book)"},
{ key:"en stu/stuen/stuer/stuene ", value:"living room"},
{ key:"en spisestue/spisestuen/spisestuer/spisestuene ", value:"diningroom"},
{ key:"en plante/planten/planter/plantene ", value:"plant"},
{ key:"en pute/puten/puter/putene ", value:"pillow"},
{ key:"myk/mykt/myke", value:" soft "},
{ key:"en dyne/dynen/dyner/dynene ", value:"dyvet, batanije"},
{ key:"en mikrobølgeovne/mikrobølgeovnen/mikrobølgeovner/mikrobølgeovnene ", value:"microwave oven"},
{ key:"en ovne/ovnen", value:"oven"},
{ key:"et enkeltrom/enkeltrommet/enkeltrommer/enkeltromene ", value:"single room"},
{ key:"enkelt", value:" single"},
{ key:"et dobbleromme/dobbletrommet ", value:"double room"},
{ key:"dobbel", value:" double"},
{ key:"en nøkkel/nøkkelen/nøkler/nøklene ", value:"key"},
{ key:"et rom/rommet/rommer/rommene ", value:"room"},
{ key:"en bar/baren", value:"bar"},
{ key:"en strand/stranden/strender/strendene ", value:"beach "},
{ key:"et fly/flyet/flyer/flyene ", value:"airplane"},
{ key:"en flyplass/flyplassen/flyplaser/flyplassene ", value:"airport"},
{ key:"en flybillete/flybilleten ", value:"plane ticket"},
{ key:"en bokhandel/bokhandelen/bokhandeler/bokhandelene ", value:"bookstore"},
{ key:"en utflukt/utflukten/utflukter/utfluktene ", value:"excursion"},
{ key:"en ettermiddag/ettermiddagen/ettermiddager/ettermiddagene ", value:"afternoon"},
{ key:"en respsjon/respsjonen/respsjoner/respsjonene ", value:"reception desk"},
{ key:"en balkong/balkongen/balkonger/balkongene ", value:"balcony"},
{ key:"et treningssenter/treningssenteret/treningssenterer/treningssenterene ", value:"gym"},
{ key:"et vindu/vinduet/vinduer/vinduene ", value:"window"},
{ key:"en dør/døren/dører/dørene", value:"door"},
{ key:"kjøkkendøren", value:"kitchen door"},
{ key:"fungerer", value:"work "},
{ key:"en dusj/dusjen/dusjer/dusjene ", value:"shower"},
{ key:"dusjer/å dusje", value:"shower"},
{ key:"internett", value:"internet"},
{ key:"nett", value:" online/internet "},
{ key:"ødelagt", value:" broken"},
{ key:"pappaen", value:"dad, baba "},
{ key:"en mamma/mammaen", value:"mama"},
{ key:"en bil/bilen/biler/bilene ", value:"car"},
{ key:"reiser/å reise", value:"travel"},
{ key:"reiste", value:" travelled "},
{ key:"et kontor/kontoret/kontorer/kontorene ", value:"office"},
{ key:"taco", value:" taco"},
{ key:"tacofredag", value:" taco friday"},
{ key:"en runstykk/runstykken/runstykker/runstykkene ", value:"rolls"},
{ key:"en sjef/sjefen/sjefer/sjefene ", value:"boss"},
{ key:"en motorsykkel/motorsykkelen/motorsykkeler/motorsykkelene ", value:"motorcycle"},
{ key:"en sykkel/sykkelen/sykler/syklene ", value:"bicycle"},
{ key:"gift", value:" married"},
{ key:"førnoyd", value:" content, pleased"},
{ key:"pepper", value:" pepper"},
{ key:"et salt/saltet/salter/saltene ", value:"salt"},
{ key:"salt", value:" salty "},
{ key:"saltest", value:"saltiest"},
{ key:"en tomat/tomaten/tomater/tomatene ", value:"tomato"},
{ key:"en frukt/frukten/frukter/fruktene ", value:"fruit"},
{ key:"en favorittmat/favorittmaten ", value:"favorite food"},
{ key:"allergisk", value:"allergic"},
{ key:"et nøt/nøtten/nøtter/nøttene ", value:"nut"},
{ key:"en saus/sausen/sauser/sausene ", value:"sauce"},
{ key:"senep", value:" mustard"},
{ key:"en grønsak/grønsaken/grønsaker/grønsakene ", value:"vegetable"},
{ key:"en spinat/spinaten ", value:"spinach"},
{ key:"en flaske/flasken/flasker/flaskene ", value:"bottle"},
{ key:"en sjokolade/sjokoladen ", value:"choccoloate bar"},
{ key:"fersk/ferske", value:" fresh "},
{ key:"ferskvann", value:" fresh watter"},
{ key:"ferskest", value:"freshest"},
{ key:"sunn/sunt/sunne ", value:" healthy "},
{ key:"igen", value:" again "},
{ key:"et hjert/hjertet/hjerter/hjertene ", value:"heart"},
{ key:"en tante/tanten/tanter/tantene ", value:"aunt"},
{ key:"et fjell/fjellet/fjeller/fjellene ", value:"mountain"},
{ key:"et basseng/bassenget/bassenger/bassengene ", value:"pool"},
{ key:"en konsert/konserten/konserter/konsertene ", value:"concert"},
{ key:"en lampe/lampen/lamper/lampene ", value:"lamp"},
{ key:"en pasta/pastaen/pastaer/pastaene ", value:"pasta"},
{ key:"mørk", value:" dark"},
{ key:"en dato/datoen/datoer/datoene ", value:"date"},
{ key:"en date/daten/dater/datene ", value:"date "},
{ key:"stenge/å stenge ", value:"close"},
{ key:"stengte", value:" closed"},
{ key:"stengt", value:" closed "},
{ key:"stengt", value:" closed "},
{ key:"lukker/å lukke", value:"close "},
{ key:"lukket", value:" closed"},
{ key:"en legitimasjon/legitimasjonen/legitimasjoner/legitimasjonene ", value:" identification"},
{ key:"varer/å vare", value:"last "},
{ key:"varte", value:" lasted "},
{ key:"være", value:"be "},
{ key:"vært", value:" been "},
{ key:"en voksen/voksen/voksne/voksne ", value:"adult"},
{ key:"vokser/å vokse", value:"grow up"},
{ key:"filmen", value:"film "},
{ key:"en skrekkfilm/skrekkfilmen/skrekkfilmer/skrekkfilmene ", value:"horror film"},
{ key:"skrekk", value:" scary"},
{ key:"en kalendar/kalendaren/kalendarer/kalendarene ", value:"calendar"},
{ key:"kort/korte", value:" short, quick "},
{ key:"et kamera/kameraet/kameraer/kameraene ", value:"photo camera"},
{ key:"tilbringer/å tilbringe ", value:"spend "},
{ key:"tilbake", value:" back "},
{ key:"bak", value:" behind "},
{ key:"en lekse/leksen/lekser/leksene ", value:"homework"},
{ key:"en ferie/ferien/ferier/feriene ", value:"vacation "},
{ key:"visum", value:"visa "},
{ key:"en toll/tollen/toller/tollene ", value:"customs"},
{ key:"en penn/pennen/penner/pennene ", value:"pen "},
{ key:"riktig", value:" correct"},
{ key:"et øyeblikk/øyeblikket/øyeblikk/øyeblikkene ", value:"moment "},
{ key:"et øye/øyet/øyner/øynene ", value:"eye "},
{ key:"en blikk/blikken/blikker/blikkene ", value:"gaze"},
{ key:"et skjema/skjemaet/skjemaer/skjemaene ", value:"form "},
{ key:"skinner/å skinne ", value:"shine "},
{ key:"en ryggsekk/ryggsekken/ryggsekker/ryggsekkene ", value:"backpack"},
{ key:"flyr/å fly", value:"fly"},
{ key:"en hytte/hytten/hytter/hyttene ", value:"cabin"},
{ key:"tung/tungt/tunge ", value:" heavy "},
{ key:"et problem/problemet/problemer/problemene ", value:"problem"},
{ key:"en ordbok/ordboken/ordboker/ordbokene ", value:"dictionary"},
{ key:"ordet", value:"word "},
{ key:"briller", value:"glasses "},
{ key:"en koffert/kofferten/kofferter/koffertene ", value:"suitcase"},
{ key:"et slott/slottet/slotter/slottene ", value:"castle"},
{ key:"en turist/turisten/turister/turistene ", value:"turist"},
{ key:"pakker/å pakke", value:"pack"},
{ key:"pakken", value:"package "},
{ key:"full/fullt/fulle ", value:" full "},
{ key:"sennep", value:" mustard"},
{ key:"mediterer", value:" meditate"},
{ key:"fordi", value:" because"},
{ key:"løper/å lope", value:"run "},
{ key:"våte/vatt", value:" wet "},
{ key:"maraton", value:" marathon"},
{ key:"meter", value:" meter "},
{ key:"kilometer", value:" kilometer"},
{ key:"sykler/å sykle", value:"ride "},
{ key:"kjedelig", value:" bored "},
{ key:"snart", value:" soon"},
{ key:"endelig", value:" finally"},
{ key:"slekt", value:" kin, family"},
{ key:"en slektninge/slektningen/slektninger/slektningene ", value:"relative"},
{ key:"telefonnummer", value:" telephone number"},
{ key:"punktlig", value:" punctual"},
{ key:"spørsmålet", value:"question "},
{ key:"spør/å spørre", value:"ask "},
{ key:"spørt", value:" asked"},
{ key:"spor/å spore", value:"track,trace"},
{ key:"et spor/sporet/spor/sporene ", value:"track "},
{ key:"førerkort", value:" drivers license "},
{ key:"e_postadressen", value:"email "},
{ key:"datamaskinen", value:"computer "},
{ key:"null", value:" zero, none"},
{ key:"pausen", value:"pause, break "},
{ key:"en kollegae/kollegaen/kollegaer/kollegaene ", value:"colleague"},
{ key:"arbeidsledig", value:" unemployed "},
{ key:"henter/å hente", value:"pick up "},
{ key:"en pose/posen/poser/posene ", value:"bag"},
{ key:"en kurv/kurven/kurver/kurvene ", value:"basket"},
{ key:"en appelsin/appelsinen/appelsiner/appelsinene ", value:"orange"},
{ key:"gratis", value:" gratis"},
{ key:"en kunde/kunden/kunder/kundene ", value:"customer"},
{ key:"en pære/pæren/pærer/pærene ", value:"pear"},
{ key:"juicen", value:"juice "},
{ key:"en kasse/kassen/kasser/kassene ", value:"cash register"},
{ key:"en agurke/agurken/agurker/agurkene ", value:"cucumber"},
{ key:"en kvittering/kvitteringen/kvitteringer/kvitteringene ", value:"recepit"},
{ key:"selger/å serge", value:"sell"},
{ key:"igjen", value:" again "},
{ key:"en slakter/slakteren/slakterer/slakterene ", value:"butcher"},
{ key:"et konditorie/konditoriet/konditorier/konditoriene ", value:"pastry shop"},
{ key:"sommerblomsten", value:"summer flowers"},
{ key:"nok", value:" enough"},
{ key:"en hatt/hatten/hatter/hattene ", value:"hat"},
{ key:"kul", value:" cool"},
{ key:"kulere", value:" cooler"},
{ key:"en jakke/jakken/jakker/jakkene ", value:"jacket"},
{ key:"en veske/vesken/jesker/veskene ", value:"purse"},
{ key:"en bukse/buksen/bukser/buksene ", value:"pants"},
{ key:"en sokk/sokken/sokker/sokkene ", value:"sock"},
{ key:"sandaler", value:"sandals "},
{ key:"en kart/karten/karter/kartene ", value:"map "},
{ key:"fyller", value:"fill, turn "},
{ key:"inviterer/å invitere ", value:"invite"},
{ key:"vasker/å vaske", value:"wash "},
{ key:"vasket", value:" have washed "},
{ key:"sint", value:" mad "},
{ key:"leien", value:"rent "},
{ key:"leier", value:"rent "},
{ key:"rotete", value:" messy "},
{ key:"venter/å vent", value:"wait"},
{ key:"ventende", value:" waiting"},
{ key:"lat/lat/late", value:" lazy "},
{ key:"tilhører", value:"belong "},
{ key:"dagligvarene", value:"groceries"},
{ key:"sitter/å sitt", value:"sit"},
{ key:"satt", value:" sat "},
{ key:"tomme", value:" empty "},
{ key:"ferdig/ferdige", value:" done "},
{ key:"høflig", value:" polite"},
{ key:"uhøflige", value:" impolite "},
{ key:"et gulve/gulvet/gulver/gulvene ", value:"floor "},
{ key:"eier/å eie", value:"own "},
{ key:"eierne", value:"owners"},
{ key:"hjelpsomt/hjelpsomme ", value:" helpful"},
{ key:"ryddig", value:" tidy"},
{ key:"ryddigst", value:" tidyest"},
{ key:"rydder", value:"tidy"},
{ key:"ryddet", value:" tidied"},
{ key:"et hysarbeide/hysarbeidet/hysarbeider/hysarbeidene ", value:"chore, housework"},
{ key:"arbeidet", value:"work"},
{ key:"kua", value:"cow "},
{ key:"spansk", value:" spanish "},
{ key:"bagasjen", value:"luggage "},
{ key:"Europa", value:" europe"},
{ key:"Asia", value:" asia"},
{ key:"ganske", value:" quite "},
{ key:"sanden", value:"sand "},
{ key:"verden", value:"world "},
{ key:"over", value:" of, covering "},
{ key:"over", value:" finished "},
{ key:"sjampanje", value:" shampagne"},
{ key:"bra jobba", value:" well done"},
{ key:"praktisk/praktiske ", value:" practical"},
{ key:"et tre/treet/trær/trærne ", value:"tree "},
{ key:"viser/å vise", value:"show "},
{ key:"farlig/farlige", value:" dangerous "},
{ key:"farligere", value:" more dangerous"},
{ key:"savner/å savne", value:"miss "},
{ key:"gir/å gi", value:"give "},
{ key:"ga", value:" gave"},
{ key:"gitt", value:" given"},
{ key:"en skole/skolen/skoler/skolene ", value:"school"},
{ key:"en post/posten", value:"mail"},
{ key:"et postkontor/postkontoret ", value:"postoffice"},
{ key:"en bygning/bygningen//bygningene ", value:"building"},
{ key:"bruker/å bruke", value:"use"},
{ key:"brukte", value:" used, spent"},
{ key:"bruk", value:" use "},
{ key:"favorittlaget", value:"favorite team"},
{ key:"favorittbandet", value:"favorite band"},
{ key:"en niese/niesen ", value:"niece"},
{ key:"en nevø/nevøen", value:"nephew "},
{ key:"utsolgt", value:" sold out "},
{ key:"et teater/teateret ", value:"theater"},
{ key:"stadion", value:"stadium"},
{ key:"t_banen", value:"subway "},
{ key:"slags", value:" kind, type "},
{ key:"operaen", value:"opera "},
{ key:"klassisk", value:"classical "},
{ key:"ekte", value:" real "},
{ key:"en ekteman/ektemannen ", value:"husband"},
{ key:"ektepar", value:" married couple"},
{ key:"plass", value:" place, space "},
{ key:"en person/personen/personer/personene ", value:"person"},
{ key:"handler/å handle ", value:"shop for,act "},
{ key:"gratulerer", value:" congratulations "},
{ key:"gratulerer/å gratulere ", value:"congratulate"},
{ key:"en overraskelse/overraskelsen/overraskelser/overraskelsene ", value:"surprise"},
{ key:"overrasker", value:"surprise"},
{ key:"ringer/å ringe", value:"ring "},
{ key:"ringte", value:" called"},
{ key:"et bryllup/bryllupet/bryllup/bryllupene ", value:"wedding"},
{ key:"bryllupsdag", value:" wedding anniversary"},
{ key:"en rose/rosen", value:"rose flower"},
{ key:"vinner/å vinne", value:"win "},
{ key:"vunnet", value:" won "},
{ key:"vant", value:" won "},
{ key:"taper/å tape", value:"loose "},
{ key:"en sport/sporten/sport/sportene ", value:"sport"},
{ key:"en radio/radioen", value:"radio"},
{ key:"dokumentarer", value:"documentaries"},
{ key:"tegner/å tegne", value:"draw"},
{ key:"tegnefilm", value:" cartoon "},
{ key:"hviler/å hvile", value:"rest"},
{ key:"en partner/partneren ", value:"partner"},
{ key:"en ambassade/ambassaden ", value:"embassy"},
{ key:"ærend", value:" erand "},
{ key:"et passfoto/passfotoet ", value:"passport foto"},
{ key:"et fødested/fødestedet ", value:"birthplace"},
{ key:"fornyer/å fornye ", value:"renew"},
{ key:"svarer/å svar", value:"answer "},
{ key:"svarte", value:" answered "},
{ key:"svart", value:" have answered "},
{ key:"betyr/å bety", value:"mean "},
{ key:"betydning", value:" meaning"},
{ key:"hjelper/å hjelpe ", value:"help"},
{ key:"en konto/kontoen/kontoer ", value:"account"},
{ key:"en bankkonto/bankkontoen/bankkontoer ", value:"bank account"},
{ key:"oppretter/å opprete ", value:"set up, start upp"},
{ key:"årsak", value:" worry, problem "},
{ key:"vanlig/vanlige", value:" usual "},
{ key:"vanligvis", value:" usually "},
{ key:"en trikke/trikken/trikker ", value:"trams, tramvaj"},
{ key:"overfører/å overføre ", value:"transfer,transmit"},
{ key:"en parkeringsplass/parkeringsplassen/parkeringsplasser/parkeringsplassene ", value:"parking place, parking lot"},
{ key:"viktig/vigtike", value:" important "},
{ key:"pen/pene/pent", value:" pretty, nice, handsome"},
{ key:"definitivt", value:" definitely"},
{ key:"difinitive", value:" definite"},
{ key:"et liv/livet/liv/livene ", value:"life"},
{ key:"synes", value:"seem, think "},
{ key:"syntes", value:" seemed"},
{ key:"enig", value:" agree, in agreement "},
{ key:"uenige", value:" disagree"},
{ key:"sannsynligvis", value:" probably"},
{ key:"sliten", value:" exhausted"},
{ key:"slitsom", value:" exhausting"},
{ key:"hater/å hate", value:"hate"},
{ key:"hatet", value:" hated"},
{ key:"rar/rare/rartt", value:" strange"},
{ key:"forferdelig", value:" terrible"},
{ key:"en bestevennen/bestevennen ", value:"best friend"},
{ key:"forkjølet", value:" sick, cold "},
{ key:"kunne", value:" could "},
{ key:"en stemninge/stemningen ", value:"mood, atmosphere"},
{ key:"forrige", value:" previous, last "},
{ key:"hverandre", value:" eachother, oneanother"},
{ key:"bærer/å bære", value:"carry "},
{ key:"flytter/å flytte ", value:"move "},
{ key:"flyttet", value:" moved"},
{ key:"en flytting/flyttingen ", value:"move"},
{ key:"en arm/armen/armer/armene ", value:"arm"},
{ key:"en rygg/ryggen", value:"back"},
{ key:"en hend/henden/hender/hendene ", value:"hands "},
{ key:"en fot/foten/føtter/føttene ", value:"feet"},
{ key:"begge/begge to", value:" both"},
{ key:"ro", value:" peace"},
{ key:"rolig", value:" calm, calmly"},
{ key:"urolig", value:" disturbed"},
{ key:"en gavekort/gavekorten ", value:"giftcard"},
{ key:"et smørbrød/smørbødet ", value:"sandwitch"},
{ key:"en sitron/sitronen/sitroner/sitronene ", value:"lemon"},
{ key:"en kokk/kokken/kokker/kokkene ", value:"cook"},
{ key:"kokker", value:"cook"},
{ key:"kokte", value:" cooked"},
{ key:"et jordbær/jordbæret/jordbær/jordbærene ", value:"strawberry"},
{ key:"jordbaerkaken", value:"strawberry cake"},
{ key:"en vegetarianer/vegetarianeren ", value:"vegetarian"},
{ key:"bakevarer/bakevarene ", value:"baked goods"},
{ key:"en pizza/pizzaen/pizzaer/pizzaene ", value:"pizza"},
{ key:"jul", value:" Christmas"},
{ key:"ribbe", value:" pork belly"},
{ key:"pinnekjøtt", value:" lamb ribs"},
{ key:"nyttårsaften", value:" new years eve"},
{ key:"julaften", value:" christmas eve"},
{ key:"julebord", value:" christmas party"},
{ key:"på forhånd", value:" behorehand, in advance "},
{ key:"til og med", value:" even, also"},
{ key:"en leke/leken/leker/lekene ", value:"toy"},
{ key:"ønsker/å ønske", value:"wish"},
{ key:"å gjøre noe med ", value:"do something about "},
{ key:"en maling/malingen/malinger/malingene", value:"paint"},
{ key:"maler/å male", value:"paint "},
{ key:"malt", value:" painted "},
{ key:"en maler/maleren/malere/malerne ", value:" painter"},
{ key:"en eske/esken/esker/eskene ", value:"box"},
{ key:"en peis/pesen/peiser/peisene ", value:"fireplace "},
{ key:"en møbel/møbelen/møbler/møblene ", value:"furniture "},
{ key:"en kommode/kommoden/komoder/komodene ", value:"dresser"},
{ key:"lås/å lås", value:"lock"},
{ key:"låste", value:" locked"},
{ key:"et hull/hullet/hull/hullene", value:"hole"},
{ key:"et hjørne/hjørnet/hjørner/hjørnene ", value:"corner"},
{ key:"rundt", value:" around, approximately "},
{ key:"en fryser/fryseren/frysere/frysere ", value:"freezer"},
{ key:"et tak/taket/tak/takene ", value:"roof, ceiling"},
{ key:"et loft/loftet/loft/loftene", value:"attic"},
{ key:"en etasje/etasjen/etasjer/etasjene ", value:"floor"},
{ key:"en duk/duken/duker/dukene ", value:"tablecloth"},
{ key:"setter/å sette", value:"place "},
{ key:"legger/å legge", value:"put down, lay "},
{ key:"putter/å putte", value:"put"},
{ key:"en kjeller/kjelleren/kjellere/kjellerne ", value:"basement"},
{ key:"et speil/speilet/speil/speilene ", value:"mirror"},
{ key:"støv", value:"dust"},
{ key:"en blyant/blyanten/blyanter/blyantene ", value:"pencil"},
{ key:"en fjernkontroll/fjernkontrollen ", value:"remote control"},
{ key:"dørmatte", value:"doormat "},
{ key:"definitiv/definitivt ", value:" definitely "},
{ key:"stikker/å stikke ", value:" run off "},
{ key:"før", value:" before "},
{ key:"en vane/vanen/vaner/vanene ", value:"habit"},
{ key:"uvane", value:"bad habbit "},
{ key:"slem/slemt", value:" mean, unkind "},
{ key:"daglig/daglige", value:" daily "},
{ key:"et stoppskilt/stoppskiltet/stoppskilt/stoppskiltene ", value:"stop sign"},
{ key:"sparkesykler", value:"scooters"},
{ key:"sakte", value:" slowly"},
{ key:"saktere", value:" slower"},
{ key:"et hår/håret/hår/hårene ", value:"hair"},
{ key:"lav/lavt/lave", value:" low, short "},
{ key:"lavere", value:" lower"},
{ key:"laveste", value:" lowest"},
{ key:"et bein/beinet/bein/beina ", value:"leg, bone "},
{ key:"en dress/dressen/dresser/dressene ", value:"suit"},
{ key:"et frak/fraket/frakker/frakkene", value:"coat"},
{ key:"en bane/banen/baner/banene ", value:"field"},
{ key:"fotballbannen", value:"soccer field"},
{ key:"en løk/løken/løker/løkene ", value:"onion "},
{ key:"en sopp/soppen/sopp/soppene ", value:"mushroom"},
{ key:"søndagsåpne", value:" open on sunday"},
{ key:"en hamburger/hamburgeren/hamburgere/hamburgerne ", value:"hamburger"},
{ key:"rulleskøytene", value:"rollerskates "},
{ key:"loppemarkedet", value:"flea market "},
{ key:"en heis/heisen/heiser/heisene ", value:"elevator"},
{ key:"under", value:" under"},
{ key:"et undertøy/undertøyet/undertøyer/undertøyene ", value:"underwear"},
{ key:"et skjegg/skjegget/skjegg/skjeggene ", value:"beard"},
{ key:"smykker", value:" jewlery"},
{ key:"et halskjede/halskjedet/halskjeder/halskjedene ", value:"necklace"},
{ key:"blond", value:" blond haired"},
{ key:"en lomme/lommen/lommer/lommene ", value:"pocket"},
{ key:"en lommebok/lommeboken/lommebøker/lommebøkene", value:"wallet"},
{ key:"passer/å passe", value:"fit "},
{ key:"passer på", value:"look after "},
{ key:"trang", value:" tight, narrow "},
{ key:"en knapp/knappen/knapper/knappene ", value:"button"},
{ key:"perfekt", value:" perfectly"},
{ key:"verktøykasse", value:" worktoolbox"},
{ key:"et bilde/bildet/bilder/bildene ", value:"photo, picture"},
{ key:"en båt/båten/båter/båtene ", value:"boat"},
{ key:"en natur/naturen/naturer/naturene ", value:"nature"},
{ key:"en innsjøe/innsjøen/innsjøer/innsjøene", value:"lake"},
{ key:"en temperatur/temperaturen/temperaturer/temperaturene ", value:"temperature"},
{ key:"en grad/graden/grader/gradene ", value:"degree"},
{ key:"celsius", value:" celcius"},
{ key:"gjennom", value:" through"},
{ key:"leiebilen", value:"rental car"},
{ key:"forlater/å forlate ", value:"leave "},
{ key:"forlot", value:" left"},
{ key:"en klokke/klokken/klokker/klokkene ", value:"watch "},
{ key:"vekkerklokken", value:"alarm clock"},
{ key:"en rutine/rutinen/rutiner/rutinene ", value:"routine"},
{ key:"dusjer", value:"shower"},
{ key:"en tann/tannen/tenner/tennene ", value:"tooth"},
{ key:"syltetøyet", value:"jam"},
{ key:"pusser", value:"clean, polish "},
{ key:"en gård/gården/gårder/gårdene ", value:"farm"},
{ key:"et blad/bladet/blader/bladene ", value:"magazine"},
{ key:"et selskap/selskapet/selskaper/selskapene ", value:"company"},
{ key:"en fugl/fuglen/fugler/fuglene ", value:"bird"},
{ key:"en elg/elgen/elger/elgene ", value:"moose, elk"},
{ key:"en and/anden/ander/endene ", value:"duck"},
{ key:"en hest/hesten/hester/hestene ", value:"horse"},
{ key:"en bjørn/bjørnen/bjørner/bjørnene ", value:"bear"},
{ key:"en edderkopp/edderkoppen/edderkopper/edderkoppene ", value:"spider"},
{ key:"lukter/å lukte", value:"smell "},
{ key:"en mus/musen/mus/musene ", value:"mouse"},
{ key:"en ulv/ulven/ulver/ulvene ", value:"wolf"},
{ key:"en veterinær/veterinæren/veterinæren/veterinærene ", value:"veterinary "},
{ key:"et bånd/båndet/bånd/båndene ", value:"leash, ribbon"},
{ key:"måte", value:" way, manner "},
{ key:"agurktid", value:" slow news season "},
{ key:"folk", value:" people"},
{ key:"sist/siste", value:" e fundit, last, last time "},
{ key:"mister/å miste", value:"loose "},
{ key:"mistet", value:" lost "},
{ key:"ligger/å ligge", value:"lie "},
{ key:"ligget", value:" lay, was lying "},
{ key:"lå", value:" qe, lay "},
{ key:"en anelse/anelsen/anelser/anelsene ", value:" idea "},
{ key:"nede", value:" downstairs "},
{ key:"oppe", value:" upstairs "},
{ key:"en lur/luren/lurer/lurene ", value:"nap "},
{ key:"overalt", value:" everywhere"},
{ key:"en skuff/skuffen/skuffer/skuffene ", value:"drawer"},
{ key:"en medisin/medisinen/medisiner/medisinene ", value:"medicine"},
{ key:"heltid", value:" full time "},
{ key:"en mastergrad/mastergraden/mastergrader/mastergradene ", value:"masters degree"},
{ key:"lingvistikk", value:" linguistics"},
{ key:"informatikk", value:" computer science"},
{ key:"et kurs/kurset/kurs/kursene ", value:"course"},
{ key:"en forelesning/forelesningen/forelesninger/forelesningene ", value:"lecture"},
{ key:"en karakter/karakteren/karakterer/karakterene ", value:"grade"},
{ key:"en høyskole/høyskolen/høyskoler/høyskolene ", value:"university, college"},
{ key:"et badekar/badekaret/badekar/badekarene ", value:"bathtub"},
{ key:"et håndkle/håndkleet/håndklær/håndklærne ", value:"towel"},
{ key:"en studentbolinge/studentbolingen/studentbolinger/studentbolingene ", value:"student dorm"},
{ key:"et semester/semesteret/semestre/semesterne ", value:"semester"},
{ key:"en rockekonsert/rockekonserten/rockekonserter/rockekonsertene ", value:"rock consert"},
{ key:"en fyr/fyren/fyrer/fyrene ", value:"guy"},
{ key:"en trom/trommen/trommer/trommene ", value:"drums"},
{ key:"en musiker/musikeren/musikere/musikerne ", value:"musician"},
{ key:"en scene/scenen/scener/scenene ", value:"stage "},
{ key:"en smarttelefone/smarttelefonen/smarttelefoner ", value:"smart phone"},
{ key:"hvem som", value:" who "},
{ key:"favorittseng", value:" favorite song"},
{ key:"et album/albumet/album/albumene ", value:"album"},
{ key:"låner/å låne", value:"lend"},
{ key:"gråter/å gråte", value:"cry "},
{ key:"hjemmefra", value:" from home"},
{ key:"en tvilling/tvillingen/tvillinger/tvillingene ", value:" twins"},
{ key:"tvillingbroren", value:"twin brother "},
{ key:"hel", value:" whole "},
{ key:"en forfatter/forfatteren/forfatterer/forfatterne", value:"author "},
{ key:"bygger/å bygge", value:"build "},
{ key:"bygde", value:" built "},
{ key:"bygget", value:" built "},
{ key:"et bygg/bygget/bygg/byggene ", value:"building"},
{ key:"en robot/roboten/roboter/robotene ", value:"robot"},
{ key:"matte", value:" math"},
{ key:"en matte/matten/matter/mattene ", value:" rug"},
{ key:"drømmejobb", value:" dream job"},
{ key:"en ingeniør/ingeniøren/ingeniører/ingeniørene ", value:" engineer"},
{ key:"en pilot/piloten/piloter/pilotene ", value:" pilot"},
{ key:"et helikopter/helikopteret/helikoptre/helikoptrene ", value:"helicopter"},
{ key:"en komiker/komikeren/komikere/komikerne ", value:" comedian"},
{ key:"et landskap/landskapet/landskap/landskapene ", value:"landscape"},
{ key:"en fotograf/fotografen/fotografer/fotografene", value:"photographers"},
{ key:"en premie/premien/premier/premiene ", value:"prize"},
{ key:"tjener/å tjene ", value:"earn "},
{ key:"et miljø/miljøet/miljøer/miljøene ", value:"environment"},
{ key:"en filmstjerne/filmstjernen/filmstjerner/filmstjernene ", value:"movie star"},
{ key:"et slips/slipset/slips/slipsene ", value:"tie"},
{ key:"velger/å velge", value:"choose"},
{ key:"et belte/beltet/belter/beltene ", value:"belt"},
{ key:"et gull/gullet/gull/gullen ", value:"gold"},
{ key:"morsdagen", value:"mothersday"},
{ key:"et skinn/skinnet/skinn/skinnene ", value:"skin,leather"},
{ key:"farsdagen", value:"fathersday"},
{ key:"velger/å velge", value:"choose"},
{ key:"et salg/salget/salg/salgene ", value:" sales "},
{ key:"til salgs", value:" for sale"},
{ key:"et prøverom/prøverommet/prøverom/prøverommene ", value:" fitting rooms"},
{ key:"en plakate/plakaten/plakater/plakatene ", value:"poster"},
{ key:"khemmekontoret", value:"home office"},
{ key:"en kjøper/kjøperen/kjøpere/kjøperne ", value:"buyer"},
{ key:"en shorts/shortsen/shorts/shortsen ", value:"shorts"},
{ key:"lommepenger", value:" pocket money"},
{ key:"en skjerm/skjermen/skjermer/skjermene ", value:"screen "},
{ key:"bør", value:" should, ought to"},
{ key:"en nakke/nakken/nakker/nakkerne ", value:"neck"},
{ key:"stiv", value:" stiff"},
{ key:"en nese/nesen/neser/nesene", value:"nose "},
{ key:"et øre/øret/ører/ørene ", value:"ear"},
{ key:"blek/bleke", value:" pale "},
{ key:"regelmessig", value:" regularly"},
{ key:"alkoholen", value:"alcohol"},
{ key:"svinekjøtt", value:" pork"},
{ key:"storfekjøtt", value:" beef"},
{ key:"en tunge/tungen/tunger/tungene ", value:"tounge"},
{ key:"en kropp/kroppen/kropper/kroppene ", value:"body"},
{ key:"en helse/helsen ", value:"health"},
{ key:"en munn/munnen/munner/munnene", value:"mouth"},
{ key:"peker/å peke", value:"point "},
{ key:"pekte", value:" pointed"},
{ key:"tærne", value:"toes "},
{ key:"et ansikt/ansiktet/ansikter/ansiktene ", value:"face"},
{ key:"planer", value:" plans"},
{ key:"frekk/frekke", value:" rude "},
{ key:"i det hele tatt ", value:" at all"},
{ key:"løser/å løse", value:"solve"},
{ key:"biologi", value:" biology"},
{ key:"geografi", value:" geography"},
{ key:"en minne/minnen/minner/minnene ", value:"memory"},
{ key:"forleden", value:"other "},
{ key:"et kart/kartet", value:"map"},
{ key:"innflyttingsfest", value:" house warming party"},
{ key:"overfor", value:" accross"},
{ key:"spesielt", value:" especially"},
{ key:"kvadratmeter", value:" square meters"},
{ key:"en pølse/pølsen/pølser/pølsene ", value:"sausage"},
{ key:"et ektepar/ekteparet ", value:"married couple"},
{ key:"et potetgulle/potetgullet ", value:"chips"},
{ key:"sprøtt", value:" crispy"},
{ key:"sprø", value:" crispy"},
{ key:"sprøest", value:" crispiest"},
{ key:"en slange/slangen ", value:"snake"},
{ key:"slangeskinn", value:" snakeskin"},
{ key:"en dagbok/dagboken", value:"diary"},
{ key:"løser/å løse", value:"solve"},
{ key:"løste", value:" solved"},
{ key:"puslespill", value:" puzzles"},
{ key:"i fjor", value:" last year "},
{ key:"en kunst/kunsten ", value:" art"},
{ key:"et fag/faget/fag/fagene ", value:"subject "},
{ key:"innflyttingsfesten ", value:"housewarming party"},
{ key:"en ektefelle/ektefellen ", value:"spouse"},
{ key:"komfyren", value:"stove"},
{ key:"katedralen", value:"cathedral"},
{ key:"vinmonopolet", value:"wine monopoly"},
{ key:"utsikten", value:"view"},
{ key:"uvanlige", value:" unusual"},
{ key:"opp til meg", value:" upme"},
{ key:"sender/å sende", value:"send "},
{ key:"sendte", value:" sent"},
{ key:"mater/å mate", value:"feed"},
{ key:"et postkort/postkortet ", value:"postcard"},
{ key:"tjeneste", value:" favor"},
{ key:"et dekk/dekket/dekkene ", value:"tire"},
{ key:"flat/flatt", value:" flat "},
{ key:"skifter/å skifte ", value:"change "},
{ key:"skiftet", value:" changed"},
{ key:"en mekaniker/mekanikeren/mekanikerne ", value:"mechanic"},
{ key:"et brev/brevet/brev/brevene ", value:"letter"},
{ key:"et konvolutt/konvolutten ", value:"envelope"},
{ key:"en frimerke/frimerken/frimerker ", value:"stamp"},
{ key:"skyld", value:" sake "},
{ key:"en boks/boksen/bokser/boksene ", value:"can"},
{ key:"ølboksen", value:"beer can"},
{ key:"takker", value:"thank"},
{ key:"takket", value:" thanked"},
{ key:"sender ut", value:" send out"},
{ key:"setebelter", value:" seatbelts"},
{ key:"en sektretær/sekretæren ", value:"secretary"},
{ key:"kopiere", value:"copy"},
{ key:"dokumenter", value:" documents"},
{ key:"en konferanse/konferansen/konferanser/konferansene ", value:" conference"},
{ key:"reparerer/å reparere ", value:"repair"},
{ key:"en maskine/maskinen ", value:"machine"},
{ key:"en prest/presten/prester ", value:"priest"},
{ key:"håndverker", value:" tranesperson"},
{ key:"fritiden", value:"free time "},
{ key:"sjelden", value:" seldom, rarely"},
{ key:"bussjåføren", value:"bus driver"},
{ key:"sommerjobb", value:" summer job"},
{ key:"telefonselger", value:" telemarketer"},
{ key:"brannmennene", value:"firemen"},
{ key:"en rørlegger/rørleggeren/rørleggere /rørleggerne ", value:"plumber"},
{ key:"en elektriker/elektrikeren/elektrikere/elektrikerne ", value:"electrician"},
{ key:"overtid", value:" overtime"},
{ key:"arbeidsklærne", value:" workclothes"},
{ key:"arbeidsmiløet", value:"working environment"},
{ key:"india", value:" india"},
{ key:"gresk/greske", value:" greek "},
{ key:"en forrett/forretten ", value:"appetizer"},
{ key:"en hovedrette/hovedretten", value:"main course"},
{ key:"leveringstjenesten ", value:"delivery service"},
{ key:"tilbyr/å tilby", value:"offer"},
{ key:"tilbød", value:" offered"},
{ key:"en tallerken/tallerkenen/tallerkener/tallerkenene ", value:"plate"},
{ key:"en bønne/bønnen/bønner/bønnene ", value:"bean"},
{ key:"kaffebønner", value:" coffee beans"},
{ key:"et måltid/måltiden ", value:"meal"},
{ key:"serverer", value:"serve"},
{ key:"sur", value:" sour"},
{ key:"en laks/laksen/laks/laksene ", value:"salmon"},
{ key:"husnummeret", value:"house number"},
{ key:"postnummeret", value:"zip code"},
{ key:"smør", value:" butter"},
{ key:"hvitløk", value:" garlik"},
{ key:"oljen", value:"oil "},
{ key:"et tips/tips", value:"tip "},
{ key:"småpenger", value:" change"},
{ key:"eddik", value:" vinegar"},
{ key:"riseddik", value:" rice vinegar"},
{ key:"en rykte/rykten/rykter/ryktene ", value:"rumor"},
{ key:"sladrer/å sladre", value:"gossip"},
{ key:"lyver/å lyve", value:"lie, lying"},
{ key:"løy", value:" lied "},
{ key:"spøkelset", value:" ghost "},
{ key:"hjemsøkt", value:" haunted"},
{ key:"ond/onde", value:" evil"},
{ key:"nysgjerrig", value:" curious "},
{ key:"en heks/heksen/hekser/heksene ", value:" witch"},
{ key:"et uhyre/uhyret/uhyrer/uhyrene ", value:"monster"},
{ key:"føler/å føle", value:"feel"},
{ key:"en følelse/følelsen/følelser/følelsene ", value:" feeling"},
{ key:"en fjord/fjorden/fjorder/fjordene ", value:" fjord"},
{ key:"en forrett/forretten/forreter/forrettene ", value:"appetizer"},
{ key:"hjemsøkte", value:" haunted"},
{ key:"studentbyen", value:" student village"},
{ key:"kleshengere/kleshengerne ", value:" clothes hangers"},
{ key:"oppholder/å oppholde ", value:"reside, occupy "},
{ key:"campusen", value:"campus"},
{ key:"internasjonale", value:" international"},
{ key:"et laken/lakenet/laken/lakene ", value:"sheet"},
{ key:"ved siden av", value:" next to"},
{ key:"en vifte/viften/vifter/viftene ", value:"fan"},
{ key:"en vegg/veggen/vegger/veggene ", value:"wall"},
{ key:"en søppelbøtte/søppelbøtten/søppelbøtter/søppelbøttene ", value:"trash can "},
{ key:"en gardin/gardinen/gardiner/gardinene ", value:"curtain"},
{ key:"en lader/laderen/ladere/laderne ", value:"charger"},
{ key:"vannkoker", value:" water boiler"},
];
