const pairs = [
{ key:"hei", value:" hi"},
{ key:"hallo", value:" hello"},
{ key:"velkommen", value:" welcome "},
{ key:"takk", value:" thanks "},
{ key:"at", value:" that, which "},
{ key:"å", value:" to"},
{ key:"om", value:" about, in "},
{ key:"omtrent", value:" around "},
{ key:"den/det", value:" that "},
{ key:"denne/dette", value:" this "},
{ key:"disse", value:" these "},
{ key:"de", value:" those "},
{ key:"har", value:"have "},
{ key:"hadde", value:" had"},
{ key:"takk for sist", value:" goodsee you again"},
{ key:"går", value:"go, walk"},
{ key:"gått", value:" gone "},
{ key:"drå", value:" go"},
{ key:"dro", value:" went"},
{ key:"gikk", value:" went"},
{ key:"da", value:" then"},
{ key:"da", value:" when "},
{ key:"beklager", value:" sorry "},
{ key:"unnskyld", value:" excuse me, sorry"},
{ key:"en unnskyldning/unnskyldningen", value:"excuse, apology"},
{ key:"veldig", value:" very "},
{ key:"mye", value:" much, a lot"},
{ key:"mange", value:" many, a lot "},
{ key:"flere", value:" several"},
{ key:"hvor", value:" where, how "},
{ key:"hva", value:" what "},
{ key:"hva enn", value:" whatever "},
{ key:"hvilke/hvilket/hvilken", value:" which"},
{ key:"hvem", value:" who "},
{ key:"hvem sin/hvem sitt/hvem sine", value:" whoose "},
{ key:"hvor mye", value:" how much"},
{ key:"hvor mange", value:" how many"},
{ key:"hvor gammel", value:" how old"},
{ key:"hvordan", value:" how"},
{ key:"hvorfor", value:" why"},
{ key:"hver/hvert", value:" every, each "},
{ key:"hvis", value:" if"},
{ key:"når", value:" when "},
{ key:"koster", value:"cost"},
{ key:"kostet", value:" cost "},
{ key:"heter", value:" are called "},
{ key:"het", value:" was called"},
{ key:"her", value:" here"},
{ key:"hitt", value:" here"},
{ key:"der", value:" there "},
{ key:"mer", value:" more"},
{ key:"med", value:" with "},
{ key:"men", value:" but"},
{ key:"ikke", value:" not "},
{ key:"også", value:" also"},
{ key:"morsom/morsomme ", value:" funny "},
{ key:"gøy", value:" fun "},
{ key:"bare", value:" only"},
{ key:"bare hyggelig", value:" youre welcome "},
{ key:"hyggelig", value:" pleasant, pleasure, nice "},
{ key:"vær så snill", value:" please "},
{ key:"vær så god", value:" here you go"},
{ key:"vær", value:"be"},
{ key:"var", value:" was"},
{ key:"kanskje", value:" maybe"},
{ key:"en helg/helgen", value:"weekend "},
{ key:"god/godt/gode", value:" good "},
{ key:"bedre", value:" better "},
{ key:"best", value:" best "},
{ key:"enn", value:" than "},
{ key:"en ost/osten", value:"cheese"},
{ key:"en fisk/fisken/fisker/fiskene ", value:"fish"},
{ key:"en mat/maten", value:"food"},
{ key:"lager/å lage", value:"make"},
{ key:"lager mat", value:"make food, cook"},
{ key:"laget", value:" made"},
{ key:"et lag/laget", value:"team"},
{ key:"en gitar/gitaren/gitarer/gitarene ", value:"guitar"},
{ key:"spiller/å spille ", value:"play "},
{ key:"spilte", value:" played"},
{ key:"et spill/spillet ", value:"game "},
{ key:"hører/å hore", value:"hear, listen "},
{ key:"høres", value:" sounds "},
{ key:"hørt", value:" heard "},
{ key:"hørte", value:" heard "},
{ key:"lytter/å lytte", value:"listen "},
{ key:"en regning/regningen/regninger/regningene ", value:"bill, account"},
{ key:"en servitør/servitøren/servitører/servitørene ", value:"waiter "},
{ key:"ser/å se", value:"see "},
{ key:"ser ut", value:" looks, dukem "},
{ key:"ser frem", value:" look forwards "},
{ key:"så", value:" saw "},
{ key:"så frem", value:" was looking forwards"},
{ key:"sett", value:" seen "},
{ key:"en lege/legen/leger/legene ", value:"doctor "},
{ key:"en tannlege/tannlegen/tannleger/tannlegene ", value:"dentist"},
{ key:"et marked/markedet ", value:"market"},
{ key:"en professor/professoren ", value:"professor"},
{ key:"syk/sykt", value:" sick "},
{ key:"sjukt", value:" sickness"},
{ key:"en sykepleier/sykepleieren ", value:"nurse"},
{ key:"et sykehus/sykehuset ", value:"hospital"},
{ key:"en pille/pillen ", value:"pill"},
{ key:"snill/snillt/snille ", value:" kind, nice "},
{ key:"snillere", value:" kinder"},
{ key:"snillest", value:"kindest"},
{ key:"smart", value:" smart"},
{ key:"stressende", value:" stressful"},
{ key:"stress", value:"stress "},
{ key:"stress", value:"stress"},
{ key:"stresset", value:" stressed"},
{ key:"vanskelig/vanskelige ", value:" difficult"},
{ key:"lett", value:" easy, light "},
{ key:"lettere", value:" easier"},
{ key:"interessant", value:" interesting"},
{ key:"en jobb/jobben", value:"job"},
{ key:"jobber", value:"work "},
{ key:"jobbet", value:" worked"},
{ key:"varm/varmt", value:" warm"},
{ key:"varmere", value:" warmer, hotter"},
{ key:"kalt", value:" cold"},
{ key:"høy/høyt/høye", value:" tall "},
{ key:"høyt", value:" highly, loudly"},
{ key:"høyere", value:" higher, taller"},
{ key:"høyest", value:" highest, loudest"},
{ key:"høyre", value:" right "},
{ key:"venstre", value:" left "},
{ key:"drikker", value:"drink, drinking "},
{ key:"drikken", value:"drink "},
{ key:"drakk", value:" drank"},
{ key:"vannen", value:" water "},
{ key:"et vann/vannet", value:"water "},
{ key:"et egg/egget/egger/eggene ", value:"egg"},
{ key:"en kafe/kaféen", value:"cafeshop"},
{ key:"en kaffe/kaffen ", value:"coffee drink"},
{ key:"kaffemaskiner", value:"coffee machine"},
{ key:"melken", value:"milk "},
{ key:"et øl/ølet", value:"beer"},
{ key:"stor/stort/store ", value:" big "},
{ key:"større", value:" bigger "},
{ key:"størst", value:"biggest "},
{ key:"små", value:" small"},
{ key:"lite", value:" small "},
{ key:"litt", value:" a little "},
{ key:"litten", value:" little "},
{ key:"billig/billige", value:" cheap "},
{ key:"billiger/billigere ", value:" cheaper "},
{ key:"billigst", value:"cheapest"},
{ key:"dyr/dyrt/dyre", value:" expensive "},
{ key:"dyrere", value:" more expensive"},
{ key:"dyrest", value:" most expensive"},
{ key:"et dyr/dyret/dyr/dyrene ", value:"animal"},
{ key:"ofte", value:" often"},
{ key:"oftere", value:" more often"},
{ key:"aldri", value:" never "},
{ key:"av og til", value:" sometimes"},
{ key:"og", value:" and"},
{ key:"eller", value:" or"},
{ key:"borte", value:" away, gone "},
{ key:"lang/lange/langt", value:" far, long "},
{ key:"Norge", value:" Norway"},
{ key:"norsk", value:" norwegian "},
{ key:"Sverige", value:" Sweden"},
{ key:"fra", value:" from "},
{ key:"kommer", value:"come"},
{ key:"kom", value:" came "},
{ key:"kommet", value:" come "},
{ key:"kommer til", value:" going"},
{ key:"svømmer", value:"swim "},
{ key:"svømmet", value:" swam "},
{ key:"svømte", value:" swam "},
{ key:"svømt", value:" swam "},
{ key:"bor/å bo", value:"live, stay "},
{ key:"bodd", value:" lived "},
{ key:"bodde", value:" lived "},
{ key:"vet/å vite", value:"know"},
{ key:"visst", value:" known "},
{ key:"visste", value:" knew "},
{ key:"skriver/å skrive ", value:"write"},
{ key:"skrev", value:" wrote "},
{ key:"skrevet", value:" wrote "},
{ key:"leser/å lese", value:"read"},
{ key:"leste", value:" read "},
{ key:"lest", value:" read "},
{ key:"lærer/å lære", value:"learn "},
{ key:"en lærer/læreren ", value:"teacher (easy search larer)"},
{ key:"snakker/å snakke ", value:"speak "},
{ key:"snakket", value:" spoke "},
{ key:"et språk/språket/språker/språkene ", value:"language"},
{ key:"forstår/å forstå ", value:"understand "},
{ key:"forstod", value:" understood"},
{ key:"et land/landet/land ", value:"country"},
{ key:"en landsby/landsbyen ", value:"village"},
{ key:"en by/byen", value:"city"},
{ key:"en te/teen", value:"tea"},
{ key:"en katt/katten/katter/kattene ", value:"cat"},
{ key:"en hund/hunden/hunder/hundene ", value:"dog"},
{ key:"et brød/brødet", value:"bread"},
{ key:"en bror/broren/brødre/brødrene ", value:"brother"},
{ key:"moren", value:"mother "},
{ key:"faren", value:"father "},
{ key:"sønnen", value:"son "},
{ key:"søsteren", value:"sister "},
{ key:"søskenet", value:"sibling "},
{ key:"datteren", value:"daughter "},
{ key:"gutten", value:"boy "},
{ key:"kvinnen", value:"woman "},
{ key:"kvinneklær", value:" woman clothing"},
{ key:"mannen", value:"man, husband "},
{ key:"man", value:" you (one)"},
{ key:"konen", value:"wife "},
{ key:"jenta", value:"girl "},
{ key:"hvordan går det ", value:" how goes it"},
{ key:"det går bra", value:" it goes well"},
{ key:"går det bra?", value:" goes it well"},
{ key:"det", value:" that "},
{ key:"god morgen", value:" good morning"},
{ key:"god dag", value:" good afternoon"},
{ key:"god kveld", value:" good evening"},
{ key:"en morgen/morgenen/morgener/morgenene ", value:"morning"},
{ key:"morgnen", value:" morgnings"},
{ key:"morgningen", value:"morning"},
{ key:"kvelden", value:"evening "},
{ key:"jeg", value:" I "},
{ key:"du", value:" you"},
{ key:"han", value:" he"},
{ key:"hun", value:" she"},
{ key:"vi", value:" we"},
{ key:"dere", value:" you"},
{ key:"de", value:" they"},
{ key:"meg", value:" me "},
{ key:"har på seg", value:" is wearing "},
{ key:"deg", value:" you "},
{ key:"seg", value:" itself "},
{ key:"ham", value:" him "},
{ key:"henne", value:" her "},
{ key:"dem", value:" them"},
{ key:"deres", value:" yours, theirs"},
{ key:"oss", value:" us"},
{ key:"min/mine/mitt", value:" mine"},
{ key:"din/dine/dit", value:" yours"},
{ key:"hans", value:" his"},
{ key:"hennes", value:" hers"},
{ key:"sin/sitt/sine", value:" own's "},
{ key:"vår/vårt/våre", value:" our "},
{ key:"én/ett", value:" one"},
{ key:"to", value:" two"},
{ key:"tre", value:" three"},
{ key:"fire", value:" four"},
{ key:"fem", value:" five"},
{ key:"seks", value:" six"},
{ key:"sju", value:" seven"},
{ key:"åtte", value:" eight"},
{ key:"ni", value:" nine"},
{ key:"ti", value:" ten"},
{ key:"elleve", value:" eleven"},
{ key:"tolv", value:" twelve"},
{ key:"tretten", value:" thirteen"},
{ key:"fjorten", value:" fourteen"},
{ key:"femten", value:" fifteen"},
{ key:"seksten", value:" sixteen"},
{ key:"sytten", value:" seventeen"},
{ key:"atten", value:" eighteen"},
{ key:"nitten", value:" nineteen"},
{ key:"tjue", value:" twenty "},
{ key:"tretti", value:" thirty"},
{ key:"forti", value:" fourty"},
{ key:"femti", value:" fifty"},
{ key:"seksti", value:" sixty"},
{ key:"sytti", value:" seventy"},
{ key:"atti", value:" eighty"},
{ key:"nitti", value:" ninety"},
{ key:"hundre", value:" hundred "},
{ key:"tusen", value:" thousand"},
{ key:"tjueen", value:" twentyone"},
{ key:"tjueto", value:" twentytwo"},
{ key:"tjuetre", value:" twentythree"},
{ key:"tjuefire", value:" twentyfour"},
{ key:"fjuefem", value:" twentyfive"},
{ key:"tjueseks", value:" twentysix"},
{ key:"tjuesju", value:" twentyseven"},
{ key:"tjueåtte", value:" twentyeight"},
{ key:"tjueni", value:" twentynine"},
{ key:"første/først", value:" first"},
{ key:"andre", value:" second, other people"},
{ key:"den andre", value:"other"},
{ key:"tredje", value:" third"},
{ key:"fjerde", value:" fourth"},
{ key:"femte", value:" fifth"},
{ key:"sjette", value:" sixth"},
{ key:"sjuende", value:" seventh"},
{ key:"åttende", value:" eighth"},
{ key:"niende", value:" ninth"},
{ key:"tiende", value:" tenth"},
{ key:"ellevte", value:" eleventh"},
{ key:"tolvte", value:" twelvth"},
{ key:"trettende", value:" thirteenth"},
{ key:"fjortende", value:" fourteenth"},
{ key:"femtende", value:" fifteenth"},
{ key:"sekstende", value:" sixteenth"},
{ key:"syttende", value:" seventeenth"},
{ key:"attende", value:" eightteenth"},
{ key:"nittende", value:" nineteenth"},
{ key:"mandag", value:" Monday"},
{ key:"tirsdag", value:" Tuesday"},
{ key:"onsdag", value:" Wednessday"},
{ key:"torsdag", value:" Thursday"},
{ key:"fredag", value:" Friday"},
{ key:"lørdag", value:" Saturday"},
{ key:"sondag", value:" Sunday"},
{ key:"lørdagen", value:"Saturday "},
{ key:"på mandager", value:" mondays"},
{ key:"morsmålet", value:"mothertongue"},
{ key:"stasjonen", value:"station "},
{ key:"biblioteket", value:"biblioteke "},
{ key:"parken", value:"park "},
{ key:"kirken", value:"church "},
{ key:"hotellet", value:"hotel "},
{ key:"hotellrommet", value:"hotel room "},
{ key:"museet", value:"museum "},
{ key:"menyen", value:"menu "},
{ key:"vennen", value:"friend "},
{ key:"vennlig", value:" friendly "},
{ key:"matbutikken", value:"grocery store "},
{ key:"butikken", value:"store "},
{ key:"kinoen", value:"cinema "},
{ key:"apoteket", value:"pharmacy "},
{ key:"bakeriet", value:"bakery "},
{ key:"baker", value:"bake "},
{ key:"baker", value:" a baker"},
{ key:"ung/ungt/unge", value:" young "},
{ key:"unge", value:"young "},
{ key:"yngre", value:" younger"},
{ key:"gammel", value:" old "},
{ key:"gamle", value:" old"},
{ key:"eldre", value:" older"},
{ key:"ny/nye/nytt", value:" new"},
{ key:"nyere", value:" newer"},
{ key:"minibanken", value:"ATM "},
{ key:"banken", value:"bank"},
{ key:"journalist", value:" a journalist"},
{ key:"advokat", value:" a lawyer "},
{ key:"universitetet", value:"university "},
{ key:"januar", value:" January"},
{ key:"februar", value:" February"},
{ key:"mars", value:" Mars"},
{ key:"april", value:" April"},
{ key:"mai", value:" May"},
{ key:"juni", value:" June"},
{ key:"juli", value:" July"},
{ key:"august", value:" August"},
{ key:"september", value:" September"},
{ key:"oktober", value:" Oktober"},
{ key:"november", value:" November"},
{ key:"desember", value:" December"},
{ key:"året", value:"year "},
{ key:"årets", value:" ofyear"},
{ key:"uken", value:"week "},
{ key:"måneden", value:"month "},
{ key:"bananen", value:"bannana "},
{ key:"eplet", value:"apple "},
{ key:"salaten", value:"salad, letuce "},
{ key:"i", value:" in "},
{ key:"i en time", value:" for an hour "},
{ key:"inn/inne", value:" inside "},
{ key:"ut/ute", value:" outside "},
{ key:"utenfor", value:" outside, outside of "},
{ key:"uten", value:" without "},
{ key:"på", value:" at, on "},
{ key:"til", value:" to, of "},
{ key:"i Norge", value:" in Norway"},
{ key:"i dag", value:" today"},
{ key:"i går", value:" dje, yesterday "},
{ key:"i forgårs", value:" pardje, day before yesterday"},
{ key:"i morges", value:" this morning"},
{ key:"i morgen", value:" nesër, tomorrow"},
{ key:"i overmorgen", value:" day after tomorrow"},
{ key:"i år", value:" this year"},
{ key:"i nærheten", value:" nearby "},
{ key:"nær", value:" near "},
{ key:"nærmest", value:" nearest"},
{ key:"tiden", value:"time "},
{ key:"gjør/gjøre", value:"do "},
{ key:"gjort", value:" done "},
{ key:"gjorde", value:" did "},
{ key:"hos", value:" at, with "},
{ key:"møter", value:"meet "},
{ key:"møtet", value:"meeting "},
{ key:"møtte", value:" met "},
{ key:"møtt", value:" have met "},
{ key:"mot", value:" to, towards, against "},
{ key:"kan", value:" can "},
{ key:"står", value:"stand, stay "},
{ key:"bli", value:"stay,become "},
{ key:"ble", value:" was"},
{ key:"blitt", value:" been "},
{ key:"gaten/gata", value:"street "},
{ key:"skrike", value:"yell "},
{ key:"skriket", value:"scream "},
{ key:"halv", value:" half "},
{ key:"halvparted", value:" half of"},
{ key:"kvart", value:" quarter"},
{ key:"prater", value:"talk, chat "},
{ key:"pratet", value:" talked "},
{ key:"praten", value:"chat "},
{ key:"glemmer", value:"forget "},
{ key:"glemt", value:" forgotten"},
{ key:"glemte", value:" forgot"},
{ key:"husker", value:"remember "},
{ key:"husket", value:" remembered "},
{ key:"prøv", value:"try"},
{ key:"prøvde", value:" tried"},
{ key:"kjeksen", value:"cookie, biskote "},
{ key:"kjæledyret", value:"pet "},
{ key:"kjære", value:" dear "},
{ key:"kjæresten", value:"sweetheart, boyfriend, girlfriend "},
{ key:"kjærlighet", value:"love"},
{ key:"kjekke", value:" handsome"},
{ key:"kjedelige", value:" boring "},
{ key:"kjøkkenet", value:"kitchen "},
{ key:"kjolen", value:"dress "},
{ key:"kjøleskapet", value:"refrigerator "},
{ key:"kjøle", value:" cool"},
{ key:"skapet", value:" closet "},
{ key:"kjøpe", value:"buy "},
{ key:"kjøpesenteret", value:"shopping center, mall "},
{ key:"kjøpte", value:" bought "},
{ key:"kjører", value:"drive "},
{ key:"kjørte", value:" drove"},
{ key:"kjøttet", value:"meat "},
{ key:"klær", value:" clothes "},
{ key:"klesbutikken", value:"clothing store "},
{ key:"kler", value:"get dressed "},
{ key:"kledd", value:" dressed, clothed"},
{ key:"kjempe", value:" giant"},
{ key:"kjempefint", value:" terrific"},
{ key:"kjempetungt", value:" really heavy "},
{ key:"kjempestor", value:" really big"},
{ key:"kjempevarmt", value:" really warm"},
{ key:"kjenner", value:"know "},
{ key:"kjent", value:" known"},
{ key:"ukjent", value:" unknown"},
{ key:"kjedet", value:"chain, necklace "},
{ key:"kreften", value:"force, craft, power "},
{ key:"uhellet", value:"accident "},
{ key:"ulykken", value:"accident "},
{ key:"kødder du", value:" are you f*cking"},
{ key:"hele/helt", value:" whole, totally, completely "},
{ key:"sikkert", value:" surely"},
{ key:"forsiktig", value:" careful"},
{ key:"neste", value:" next"},
{ key:"nesten", value:" almost"},
{ key:"det eneste", value:"only thing"},
{ key:"seg selv", value:" them selves"},
{ key:"holder", value:" hold "},
{ key:"alt", value:" everything "},
{ key:"alle", value:" all, everybody "},
{ key:"altså", value:" so, therefore"},
{ key:"spiser", value:"eat "},
{ key:"spiste", value:" ate "},
{ key:"spist", value:" eaten "},
{ key:"så", value:" so, therefore "},
{ key:"må", value:" must, have"},
{ key:"måtte", value:" had to"},
{ key:"jo", value:" oncontrary "},
{ key:"faen", value:" f*ck "},
{ key:"dårlig", value:" bad "},
{ key:"verste", value:" worst "},
{ key:"fattig", value:" poor"},
{ key:"rik", value:" rich"},
{ key:"titte", value:" peek, check out"},
{ key:"tur", value:" turn, walk "},
{ key:"turen", value:"trip "},
{ key:"fjelltur", value:" mountain hike"},
{ key:"teltur", value:" camping trip"},
{ key:"til a handle", value:"act"},
{ key:"elsker", value:"love "},
{ key:"får", value:"get "},
{ key:"fått", value:" got"},
{ key:"fikk", value:" got "},
{ key:"forresten", value:" byway"},
{ key:"som", value:" like, which "},
{ key:"brenner", value:" burns"},
{ key:"skjer/å skje", value:"happen"},
{ key:"skjedde", value:" happened "},
{ key:"skjedd", value:" happened "},
{ key:"hjemme", value:" at home "},
{ key:"hjemmet", value:"home "},
{ key:"nyheten", value:"news "},
{ key:"avisen", value:" newspaper "},
{ key:"nå", value:" now"},
{ key:"sen/sent", value:" late "},
{ key:"senere", value:" later"},
{ key:"av", value:" of "},
{ key:"minst", value:" at least"},
{ key:"i hvert fall", value:" at least"},
{ key:"tror", value:" believe "},
{ key:"dritten", value:" shit "},
{ key:"selvfølgelig", value:" surely "},
{ key:"fortsatt", value:" still"},
{ key:"fortsetter", value:"continue"},
{ key:"fortsatte", value:" continued "},
{ key:"ennå", value:" yet "},
{ key:"fort", value:" fast, quickly "},
{ key:"rask", value:" fast "},
{ key:"raskest", value:"fastest"},
{ key:"sann", value:" true"},
{ key:"sant", value:" true "},
{ key:"evige", value:" eternal"},
{ key:"ilden", value:" fire "},
{ key:"bryter", value:"break, switch "},
{ key:"brukket", value:" broken"},
{ key:"mens", value:" while"},
{ key:"makt", value:" power "},
{ key:"finne", value:" find"},
{ key:"fant", value:" found "},
{ key:"funnet", value:" found "},
{ key:"forelderen", value:"parent"},
{ key:"besteforelderen ", value:"grandparent "},
{ key:"bursdagen", value:"birthday "},
{ key:"bursdagskortet", value:"birthday card "},
{ key:"dagen", value:"day "},
{ key:"natten", value:"night "},
{ key:"midnatt", value:" midnight "},
{ key:"redd", value:" afraid "},
{ key:"egentlig", value:" really "},
{ key:"virkelig", value:" really, truly"},
{ key:"siden", value:" since, ago "},
{ key:"losningen", value:"solution"},
{ key:"frokosten", value:"breakfast "},
{ key:"lunsjen", value:"lunch "},
{ key:"middagen", value:"dinner "},
{ key:"kveldsmat", value:" supper"},
{ key:"sier", value:"say "},
{ key:"sa", value:" said "},
{ key:"sagt", value:" said "},
{ key:"sier", value:"say "},
{ key:"seier", value:"say "},
{ key:"si ifra", value:" let me know"},
{ key:"ifra", value:" from"},
{ key:"tenker", value:"think "},
{ key:"tenkte", value:" thought"},
{ key:"gjerne", value:" like, gladly "},
{ key:"vil", value:"want "},
{ key:"ville", value:" wanted"},
{ key:"skal", value:" shall (will), going"},
{ key:"skulle", value:" would "},
{ key:"burde", value:" should "},
{ key:"skjorten", value:"shirt "},
{ key:"skjørtet", value:"skirt "},
{ key:"skoen", value:"shoe "},
{ key:"joggerskoen", value:"sneakers"},
{ key:"genser", value:"sweater "},
{ key:"intervjuet", value:"interview "},
{ key:"tar", value:"take, catch "},
{ key:"tar med", value:"bring"},
{ key:"tar på", value:" touch"},
{ key:"tatt", value:" taken, cought "},
{ key:"i det hele tatt ", value:" at all"},
{ key:"tok", value:" took "},
{ key:"tok med", value:" brought"},
{ key:"stede", value:" place "},
{ key:"stedet", value:" instead "},
{ key:"skylle", value:"rinse, flush "},
{ key:"ned", value:" down "},
{ key:"første", value:" first"},
{ key:"gangen", value:"time "},
{ key:"noen gang", value:" any time "},
{ key:"time", value:"hour "},
{ key:"time", value:"appointment"},
{ key:"noe", value:" something"},
{ key:"noen", value:" some, any "},
{ key:"noens", value:" somebody's"},
{ key:"ingenting", value:" nothing "},
{ key:"ingen", value:" noone "},
{ key:"tingen", value:"thing "},
{ key:"varet", value:"weather"},
{ key:"sol", value:" me diell, sunny "},
{ key:"solen", value:"sun "},
{ key:"regner", value:"rain, shi "},
{ key:"snør", value:"snow "},
{ key:"snøen", value:"snow "},
{ key:"overskyet", value:" me re, cloudy "},
{ key:"våren", value:"spring "},
{ key:"sommeren", value:"summer "},
{ key:"høsten", value:"fall, autumn "},
{ key:"vinteren", value:"winter "},
{ key:"kald", value:" cold "},
{ key:"varm", value:" hot "},
{ key:"synger", value:"sing "},
{ key:"sangen", value:"song "},
{ key:"koret", value:"choir "},
{ key:"alltid", value:" always"},
{ key:"jogger", value:"jog "},
{ key:"hånden", value:"hand "},
{ key:"fots", value:" foot "},
{ key:"fotball", value:" futboll "},
{ key:"kampen", value:"match, game, fight, battle "},
{ key:"fotballkampen", value:"football match"},
{ key:"ballen", value:"ball "},
{ key:"liker", value:"like, enjoy "},
{ key:"likte", value:" liked "},
{ key:"likt", value:" liked "},
{ key:"sengen", value:"bed "},
{ key:"toalettet", value:"restroom "},
{ key:"bad", value:" bath "},
{ key:"bader", value:"bathe "},
{ key:"badet", value:"bathroom "},
{ key:"baderommet", value:"bathroom"},
{ key:"badedrakten", value:"swimsuit "},
{ key:"ren/rent/rene", value:" clean "},
{ key:"restauranten", value:"restaurant "},
{ key:"romkameraten", value:"roommate "},
{ key:"soverommet", value:"bedroom "},
{ key:"sover", value:"sleep, is sleeping "},
{ key:"sov", value:" slept "},
{ key:"sovet", value:" slept "},
{ key:"sovner", value:"fall asleep"},
{ key:"sovnet", value:" fell asleep"},
{ key:"trøtt", value:" tired"},
{ key:"sliten/slitne", value:" tired "},
{ key:"billetten", value:"ticket "},
{ key:"toget", value:"train "},
{ key:"bestiller", value:"order "},
{ key:"avbestiller", value:"cancel "},
{ key:"bestillingen", value:"order "},
{ key:"betaler", value:"pay "},
{ key:"kontant", value:" cash "},
{ key:"kort", value:" card, credit card "},
{ key:"kredittkorten", value:"credit card "},
{ key:"appen", value:"application "},
{ key:"minutten", value:"minute "},
{ key:"klokka", value:" time (clock)"},
{ key:"tid", value:" time "},
{ key:"bordet", value:"table "},
{ key:"skrivebordet", value:"desk "},
{ key:"leiligheten", value:"apartment "},
{ key:"huset", value:"house "},
{ key:"stolen", value:"chair "},
{ key:"setet", value:"seat "},
{ key:"stygg", value:" ugly "},
{ key:"for", value:" too much, a lot "},
{ key:"for tiden", value:" currently, at this time"},
{ key:"på tide", value:" time"},
{ key:"vakker", value:" beautiful "},
{ key:"nettopp", value:" exactly, just "},
{ key:"flott", value:" great "},
{ key:"fint", value:" nice "},
{ key:"størrelsen", value:"(clothes) size "},
{ key:"leter", value:"look, looking"},
{ key:"etter", value:" for, after "},
{ key:"etterpå", value:" afterwards "},
{ key:"åpen", value:" open "},
{ key:"åpner", value:"open (v) "},
{ key:"åpnet", value:" opened"},
{ key:"trenger", value:"need "},
{ key:"trengte", value:" needed"},
{ key:"finner", value:"find "},
{ key:"fant", value:" found"},
{ key:"finner sted", value:"take place"},
{ key:"fant sted", value:" took place"},
{ key:"avgangen", value:"departure "},
{ key:"onkel", value:"uncle "},
{ key:"fantastisk", value:" fantastic"},
{ key:"hyllen", value:"shelf "},
{ key:"teppet", value:"carpet "},
{ key:"teppet", value:"blanket "},
{ key:"blir", value:"come up to, costs, make "},
{ key:"blir", value:"become "},
{ key:"blir du med", value:" are you comming along, will you become"},
{ key:"ledig", value:" free, available"},
{ key:"forsinket", value:" delayed"},
{ key:"bestefar", value:" grandfather "},
{ key:"bestemor", value:" grandmother "},
{ key:"søt", value:" sweet "},
{ key:"sukker", value:" sugar"},
{ key:"rett", value:" straight"},
{ key:"frem", value:" ahead "},
{ key:"dyrehagen", value:"zoo "},
{ key:"elven", value:"river "},
{ key:"besøker", value:"visit "},
{ key:"besøk", value:"visitor "},
{ key:"besøkt", value:" visited "},
{ key:"besøkte", value:" visited "},
{ key:"sentrum", value:" center "},
{ key:"sulten", value:" hungry"},
{ key:"tørst", value:" thirsty "},
{ key:"bussen", value:"bus "},
{ key:"bussholdeplassen ", value:"bus stop"},
{ key:"bussbilleten", value:"bus ticket"},
{ key:"busstasjonnen", value:"bus station"},
{ key:"pengene", value:"money "},
{ key:"nummeret", value:"number "},
{ key:"taxien", value:"taxi "},
{ key:"taxituren", value:"taxiride "},
{ key:"adressen", value:"adress "},
{ key:"gjentar", value:"repeat "},
{ key:"deler", value:"split, divide, share "},
{ key:"familien", value:"family "},
{ key:"suppen", value:"soup "},
{ key:"nervøs", value:" nervous"},
{ key:"hodet", value:"head "},
{ key:"vondt", value:" hurt, pain "},
{ key:"trist", value:" sad"},
{ key:"glad/glade", value:" happy "},
{ key:"mindre", value:" less, smaller "},
{ key:"minste", value:" smallest"},
{ key:"smaker", value:"taste, tastes "},
{ key:"håpen", value:"hope "},
{ key:"håper", value:"hope "},
{ key:"forhåpentligvis ", value:" hopefully"},
{ key:"glass", value:"glass "},
{ key:"festen", value:"party "},
{ key:"fester", value:"party "},
{ key:"brusen", value:"soda "},
{ key:"invitasjonen", value:"invitation "},
{ key:"rodvinen", value:"read wine"},
{ key:"hjemme", value:" home "},
{ key:"hurra", value:" urra, horay, hooray"},
{ key:"bandet", value:"band "},
{ key:"ballongen", value:"balloon "},
{ key:"klovnen", value:"clown "},
{ key:"gjest", value:"guest "},
{ key:"gaven", value:"gift "},
{ key:"lar", value:"let "},
{ key:"danser", value:"dance "},
{ key:"danset", value:" danced"},
{ key:"feirer", value:"celebrate "},
{ key:"musikken", value:"music "},
{ key:"navnet", value:"name "},
{ key:"fornavnet", value:"first name "},
{ key:"etternavnet", value:"last name "},
{ key:"bedring", value:" recovery "},
{ key:"feber", value:" fever"},
{ key:"frisk", value:" healthy"},
{ key:"lenger", value:" anymore "},
{ key:"lenge", value:" long "},
{ key:"festivalen", value:"festival "},
{ key:"starter", value:"start "},
{ key:"begynte", value:" began, started"},
{ key:"slutter", value:"end, stop, quit "},
{ key:"slutten", value:"end "},
{ key:"avslutte", value:" finish"},
{ key:"til slutt", value:" finally"},
{ key:"studerer", value:"study "},
{ key:"drar", value:"go, leave "},
{ key:"skogen", value:"forest "},
{ key:"skogkatten", value:"forest cat "},
{ key:"dessverre", value:" unfortunately"},
{ key:"allerede", value:" already"},
{ key:"lyst", value:"want"},
{ key:"et lys/lyset", value:"light"},
{ key:"lys", value:" bright, light "},
{ key:"planen", value:"plan "},
{ key:"instrumentet", value:"instrument "},
{ key:"videospill", value:" videogame"},
{ key:"podkast", value:" podcast "},
{ key:"grillen", value:"grill "},
{ key:"griller", value:"grill "},
{ key:"grillet", value:" grilled"},
{ key:"grillfesten", value:"barbequeue "},
{ key:"pianoen", value:"piano "},
{ key:"skitten", value:" dirty"},
{ key:"babyen", value:"baby "},
{ key:"barnet", value:"child "},
{ key:"barnebarnet", value:"grandchild "},
{ key:"historien", value:"history "},
{ key:"fransk", value:" french"},
{ key:"amerikansk", value:" american "},
{ key:"svensk", value:" swedish"},
{ key:"studenten", value:"student "},
{ key:"fiolinen", value:"violin "},
{ key:"hobbyen", value:"hobby"},
{ key:"tennis", value:" tennis"},
{ key:"pariserhjulet", value:"ferris wheel "},
{ key:"tidlig", value:" early "},
{ key:"tidligere", value:" earlier"},
{ key:"pommes fritesen ", value:"fried potatoes, french fries"},
{ key:"trener", value:"train, exercise "},
{ key:"koppen", value:"cup "},
{ key:"yoghurten", value:"yogurt "},
{ key:"frokostblanding ", value:" cereal"},
{ key:"risen", value:"rice "},
{ key:"isen", value:"icecream "},
{ key:"kyllingen", value:"chicken "},
{ key:"hagen", value:"garden "},
{ key:"alene", value:" alone "},
{ key:"sammen", value:" together "},
{ key:"trappen", value:"staircase, stairs "},
{ key:"kollektivet", value:"shared apartment "},
{ key:"leilighetsbygget", value:"apartment building "},
{ key:"hvit/hvitt/hvite ", value:" white "},
{ key:"svart/svarte", value:" black "},
{ key:"rød/rødt/røde", value:" red "},
{ key:"grønn/grønt/grønne ", value:" green "},
{ key:"lilla", value:" purple"},
{ key:"oransje", value:" orange color"},
{ key:"gul/gult/gule", value:" yellow "},
{ key:"grå/grått/grå", value:" gray "},
{ key:"blå/blått/blå", value:" blue "},
{ key:"lyseblå", value:" light blue"},
{ key:"rosa", value:" pink"},
{ key:"brun/brunt/brune", value:" brown"},
{ key:"grønnsaken", value:"vegetable "},
{ key:"naboen", value:"neighbor "},
{ key:"nabolaget", value:"neighborhood "},
{ key:"skit/skitne", value:" dirty "},
{ key:"stille", value:" quiet"},
{ key:"stillere", value:" quieter"},
{ key:"foretrekker", value:" prefer"},
{ key:"vasen", value:"vase "},
{ key:"blomsten", value:"flower "},
{ key:"boken", value:"book "},
{ key:"stuen", value:"living room "},
{ key:"spisestuen", value:"diningroom "},
{ key:"planten", value:"plant "},
{ key:"puten", value:"pillow "},
{ key:"myk", value:" soft"},
{ key:"dynen", value:"dyvet, batanije "},
{ key:"mikrobølgeovner ", value:"microwave oven "},
{ key:"ovnen", value:"oven "},
{ key:"enkeltrommet", value:"single room "},
{ key:"enkelt", value:" single"},
{ key:"dobbletrommet", value:"double room "},
{ key:"dobbel", value:" double"},
{ key:"nøkkel", value:"key "},
{ key:"rommet", value:"room "},
{ key:"baren", value:"bar "},
{ key:"stranden", value:"beach "},
{ key:"flyet", value:"airplane "},
{ key:"flyplassen", value:"airport "},
{ key:"flybilleten", value:"plane ticket "},
{ key:"bokhandelen", value:"bookstore "},
{ key:"utflukten", value:"excursion "},
{ key:"ettermiddagen", value:"afternoon "},
{ key:"respsjonen", value:"reception desk "},
{ key:"balkong", value:"balcony "},
{ key:"treningssenteret", value:"gym "},
{ key:"vinduet", value:"window "},
{ key:"døren", value:"door "},
{ key:"kjøkkendøren", value:"kitchen door"},
{ key:"fungerer", value:"work "},
{ key:"dusjen", value:"dush "},
{ key:"dusjer", value:"shower"},
{ key:"internett", value:"internet"},
{ key:"nett", value:" online/internet "},
{ key:"ødelagt", value:" broken"},
{ key:"pappaen", value:"dad, baba "},
{ key:"mammaen", value:"mama "},
{ key:"bilen", value:"car "},
{ key:"reiser", value:"travel "},
{ key:"reiste", value:" travelled "},
{ key:"kontoret", value:"office "},
{ key:"taco", value:" taco"},
{ key:"tacofredag", value:" taco friday"},
{ key:"runstykken", value:"rolls "},
{ key:"sjefen", value:"boss "},
{ key:"motorsykkelen", value:"motorcycle "},
{ key:"sykkelen", value:"bicycle "},
{ key:"gift", value:" married"},
{ key:"førnoyd", value:" content, pleased"},
{ key:"pepper", value:" pepper"},
{ key:"saltet", value:"salt "},
{ key:"salt", value:" salty "},
{ key:"saltest", value:"saltiest"},
{ key:"tomaten", value:"tomato "},
{ key:"frukten", value:"fruit "},
{ key:"favorittmaten", value:"favorite food"},
{ key:"allergisk", value:"allergic"},
{ key:"nøtten", value:"nut, arra "},
{ key:"sausen", value:"sauce "},
{ key:"senep", value:" mustard"},
{ key:"grønsaken", value:"vegetable "},
{ key:"spinaten", value:"spinach "},
{ key:"flasken", value:"bottle "},
{ key:"sjokoladen", value:"choccoloate bar "},
{ key:"fersk", value:" fresh "},
{ key:"ferskvann", value:" fresh watter"},
{ key:"ferskest", value:"freshest"},
{ key:"sunn/sunt/sunne ", value:" healthy "},
{ key:"igen", value:" again "},
{ key:"hjertet", value:"heart "},
{ key:"tanten", value:"aunt "},
{ key:"fjellen", value:"mountain "},
{ key:"bassenget", value:"pool "},
{ key:"konserten", value:"concert "},
{ key:"lampen", value:"lamp "},
{ key:"pastaen", value:"pasta "},
{ key:"mørk", value:" dark"},
{ key:"datoen", value:"date "},
{ key:"daten", value:"date "},
{ key:"stenge", value:"close "},
{ key:"stengte", value:" closed"},
{ key:"stengt", value:" closed "},
{ key:"stengt", value:" closed "},
{ key:"lukk", value:"close "},
{ key:"lukket", value:" closed"},
{ key:"legitimasjonen", value:" identification "},
{ key:"varer", value:"last "},
{ key:"varte", value:" lasted "},
{ key:"være", value:"be "},
{ key:"vært", value:" been "},
{ key:"voksen", value:"adult "},
{ key:"filmen", value:"film "},
{ key:"skrekkfilmen", value:"horror film "},
{ key:"skrekk", value:" scary"},
{ key:"kalendaren", value:"calendar "},
{ key:"kort/korte", value:" short, quick "},
{ key:"kameraet", value:"photo camera "},
{ key:"tilbringer", value:"spend "},
{ key:"tilbake", value:" back "},
{ key:"bak", value:" behind "},
{ key:"leksen", value:"homework "},
{ key:"ferien", value:"vacation "},
{ key:"visum", value:"visa "},
{ key:"tollen", value:"customs "},
{ key:"pennen", value:"pen "},
{ key:"riktig", value:" correct"},
{ key:"øyeblikket", value:"moment (now?) "},
{ key:"øyet", value:"eye "},
{ key:"blikken", value:"gaze "},
{ key:"skjemaet", value:"form "},
{ key:"skinner", value:"shine "},
{ key:"ryggsekken", value:"backpack "},
{ key:"flyr", value:"fly "},
{ key:"hytten", value:"cabin "},
{ key:"tung/tungt/tunge ", value:" heavy "},
{ key:"problemet", value:"problem "},
{ key:"ordboken", value:"dictionary "},
{ key:"ordet", value:"word "},
{ key:"briller", value:"glasses "},
{ key:"kofferten", value:"suitcase "},
{ key:"slottet", value:"castle "},
{ key:"turisten", value:"turist "},
{ key:"pakker", value:"pack "},
{ key:"pakken", value:"package "},
{ key:"full/fullt/fulle ", value:" full "},
{ key:"sennep", value:" mustard"},
{ key:"mediterer", value:" meditate"},
{ key:"fordi", value:" because"},
{ key:"løper", value:"run "},
{ key:"våte", value:" wet "},
{ key:"maraton", value:" marathon"},
{ key:"meter", value:" meter "},
{ key:"kilometer", value:" kilometer"},
{ key:"sykler", value:"ride "},
{ key:"skedlig", value:" bored "},
{ key:"snart", value:" soon"},
{ key:"endelig", value:" finally"},
{ key:"slekt", value:" kin, family"},
{ key:"slektningen", value:"relative "},
{ key:"telefonnummer", value:" telephone number"},
{ key:"punktlig", value:" punctual"},
{ key:"spørsmålet", value:"question "},
{ key:"spør", value:"ask "},
{ key:"spor", value:"track "},
{ key:"sporet", value:"track "},
{ key:"spørt", value:" asked"},
{ key:"førerkort", value:" drivers license "},
{ key:"e_postadressen", value:"email "},
{ key:"datamaskinen", value:"computer "},
{ key:"null", value:" zero, none"},
{ key:"pausen", value:"pause, break "},
{ key:"kollegaen", value:"colleague"},
{ key:"arbeidsledig", value:" unemployed "},
{ key:"henter", value:"pick up "},
{ key:"posen", value:"bag "},
{ key:"kurven", value:"basket "},
{ key:"appelsinen", value:"orange "},
{ key:"gratis", value:" gratis"},
{ key:"kunden", value:"customer "},
{ key:"pæren", value:"pear "},
{ key:"juicen", value:"juice "},
{ key:"kassen", value:"cash register "},
{ key:"agurken", value:"cucumber "},
{ key:"kvitteringen", value:"recepit "},
{ key:"selger", value:"sell "},
{ key:"igjen", value:" again "},
{ key:"igjen", value:" left "},
{ key:"slakteren", value:"butcher "},
{ key:"konditoriet", value:"pastry shop "},
{ key:"sommerblomsten", value:"summer flowers"},
{ key:"nok", value:" enough"},
{ key:"hatten", value:"hat "},
{ key:"kul", value:" cool"},
{ key:"jakken", value:"jacket "},
{ key:"vesken", value:"purse "},
{ key:"buksen", value:"pants "},
{ key:"sokk", value:"sock "},
{ key:"sandaler", value:"sandals "},
{ key:"karten", value:"map "},
{ key:"fyller", value:"fill, turn "},
{ key:"inviterer", value:"invite"},
{ key:"vasker", value:"wash "},
{ key:"vasket", value:" have washed "},
{ key:"sint", value:" mad "},
{ key:"leien", value:"rent "},
{ key:"leier", value:"rent "},
{ key:"rotete", value:" messy "},
{ key:"venter", value:"wait "},
{ key:"ventende", value:" waiting"},
{ key:"lat", value:" lazy "},
{ key:"tilhører", value:"belong "},
{ key:"dagligvarene", value:"groceries"},
{ key:"sitter", value:"sit "},
{ key:"satt", value:" sat "},
{ key:"tomme", value:" empty "},
{ key:"ferdig", value:" done "},
{ key:"høflig", value:" polite"},
{ key:"uhøflige", value:" impolite "},
{ key:"gulvet", value:"floor "},
{ key:"eier", value:"own "},
{ key:"eierne", value:"owners"},
{ key:"hjelpsomt/hjelpsomme ", value:" helpful"},
{ key:"ryddig", value:" tidy"},
{ key:"ryddigst", value:" tidyest"},
{ key:"rydder", value:"tidy"},
{ key:"ryddet", value:" tidied"},
{ key:"hysarbeidet", value:"chore, housework "},
{ key:"arbeidet", value:"work"},
{ key:"kua", value:"cow "},
{ key:"spansk", value:" spanish "},
{ key:"bagasjen", value:"luggage "},
{ key:"Europa", value:" europe"},
{ key:"Asia", value:" asia"},
{ key:"ganske", value:" quite "},
{ key:"sanden", value:"sand "},
{ key:"verden", value:"world "},
{ key:"over", value:" of, covering "},
{ key:"over", value:" finished "},
{ key:"sjampanje", value:" shampagne"},
{ key:"bra jobba", value:" well done"},
{ key:"praktisk/praktiske ", value:" practical"},
{ key:"treet", value:"tree"},
{ key:"viser", value:"show "},
{ key:"farlig/farlige", value:" dangerous "},
{ key:"farligere", value:" more dangerous"},
{ key:"savner", value:"miss "},
{ key:"gir/å gi", value:"give "},
{ key:"ga", value:" gave"},
{ key:"gitt", value:" given"},
{ key:"skolen", value:"school "},
{ key:"posten", value:"mail "},
{ key:"postkontoret", value:"postoffice "},
{ key:"bygningen", value:"building "},
{ key:"bruker 	", value:"use"},
{ key:"brukte", value:" used, spent"},
{ key:"bruk", value:" use "},
{ key:"favorittlaget", value:"favorite team"},
{ key:"favorittbandet", value:"favorite band"},
{ key:"niesen", value:"niece "},
{ key:"nevøen", value:"nephew "},
{ key:"utsolgt", value:" sold out "},
{ key:"teateret", value:"theater "},
{ key:"begynner", value:"begin, start "},
{ key:"stadion", value:"stadium"},
{ key:"t_banen", value:"subway "},
{ key:"slags", value:" kind, type "},
{ key:"operaen", value:"opera "},
{ key:"klassisk", value:"classical "},
{ key:"ekte", value:" real "},
{ key:"ektemannen", value:"husband "},
{ key:"ektepar", value:" married couple"},
{ key:"plass", value:" place, space "},
{ key:"personen", value:"person "},
{ key:"handler", value:"shop for,act "},
{ key:"gratulerer", value:" congratulations "},
{ key:"gratulerer", value:"congratulate "},
{ key:"overraskelsen", value:"surprise "},
{ key:"overrasker", value:"surprise"},
{ key:"ringer", value:"ring "},
{ key:"ringte", value:" called"},
{ key:"bryllupet", value:"wedding "},
{ key:"bryllupsdag", value:" wedding anniversary"},
{ key:"rosen", value:"rose flower "},
{ key:"vinner", value:"win "},
{ key:"vunnet", value:" won "},
{ key:"vant", value:" won "},
{ key:"taper", value:"loose "},
{ key:"sporten", value:"sport "},
{ key:"radioen", value:"radio "},
{ key:"dokumentarer", value:"documentaries"},
{ key:"tegner", value:"draw "},
{ key:"tegnefilm", value:" cartoon "},
{ key:"hviler", value:"rest "},
{ key:"partneren", value:"partner "},
{ key:"ambassaden", value:"embassy "},
{ key:"ærend", value:" erand "},
{ key:"passfotoet", value:"passport foto "},
{ key:"fødestedet", value:"birthplace "},
{ key:"fornyer", value:"renew "},
{ key:"svarer", value:"answer "},
{ key:"svarte", value:" answered "},
{ key:"svart", value:" have answered "},
{ key:"betyr", value:"mean "},
{ key:"betydning", value:" meaning"},
{ key:"hjelper", value:"help "},
{ key:"kontoen", value:"account "},
{ key:"bankkontoen", value:"bank account"},
{ key:"oppretter", value:"set up, start upp "},
{ key:"årsak", value:" worry, problem "},
{ key:"vanlig", value:" usual "},
{ key:"vanligvis", value:" usually "},
{ key:"trikken", value:"trams, tramvaj "},
{ key:"overfører", value:"transfer,transmit "},
{ key:"parkeringsplass ", value:"parking place, lot "},
{ key:"viktig/vigtike", value:" important "},
{ key:"pen/pene/pent", value:" pretty, nice, handsome"},
{ key:"definitivt", value:" definitely"},
{ key:"difinitive", value:" definite"},
{ key:"livet", value:"life "},
{ key:"synes", value:"seem, think "},
{ key:"syntes", value:" seemed"},
{ key:"enig", value:" agree, in agreement "},
{ key:"uenige", value:" disagree"},
{ key:"sannsynligvis", value:" probably"},
{ key:"sliten", value:" exhausted"},
{ key:"slitsom", value:" exhausting"},
{ key:"hater", value:"hate "},
{ key:"hatet", value:" hated"},
{ key:"rar/rare/rartt", value:" strange"},
{ key:"forferdelig", value:" terrible"},
{ key:"bestevennen", value:"best friend "},
{ key:"forkjølet", value:" sick, cold "},
{ key:"kunne", value:" could "},
{ key:"stemningen", value:"mood, atmosphere "},
{ key:"forrige", value:" previous, last "},
{ key:"hverandre", value:" eachother, oneanother"},
{ key:"bærer", value:"carry "},
{ key:"flytter", value:"move "},
{ key:"flyttet", value:" moved"},
{ key:"flyttingen", value:"move "},
{ key:"armen", value:"arm "},
{ key:"ryggen", value:"back "},
{ key:"hender", value:"hands "},
{ key:"føtter", value:"feet "},
{ key:"begge/begge to", value:" both"},
{ key:"ro", value:" peace"},
{ key:"rolig", value:" calm, calmly"},
{ key:"urolig", value:" disturbed"},
{ key:"gavekorten", value:"giftcard "},
{ key:"smørbødet", value:"sandwitch "},
{ key:"sitronen", value:"lemon "},
{ key:"kokken", value:"cook "},
{ key:"kokker", value:"cook"},
{ key:"kokte", value:" cooked"},
{ key:"jordbæret", value:"strawberry "},
{ key:"jordbaerkaken", value:"strawberry cake"},
{ key:"vegetarianeren", value:"vegetarian "},
{ key:"bakevarer", value:"baked goods "},
{ key:"pizzaen", value:"pizza "},
{ key:"jul", value:" Christmas"},
{ key:"ribbe", value:" pork belly"},
{ key:"pinnekjøtt", value:" lamb ribs"},
{ key:"nyttårsaften", value:" new years eve"},
{ key:"julaften", value:" christmas eve"},
{ key:"julebord", value:" christmas party"},
{ key:"på forhånd", value:" behorehand, in advance "},
{ key:"til og med", value:" even, also"},
{ key:"leken", value:"toy "},
{ key:"ønsker", value:"wish "},
{ key:"å gjøre noe med ", value:"do something about "},
{ key:"malingen", value:"paint"},
{ key:"maler", value:"paint "},
{ key:"malt", value:" painted "},
{ key:"maler", value:" painter"},
{ key:"esken", value:"box "},
{ key:"peisen", value:"fireplace "},
{ key:"gangen", value:"hallway "},
{ key:"møbelen", value:"furniture"},
{ key:"kommoden", value:"dresser "},
{ key:"lås", value:"lock "},
{ key:"låste", value:" locked"},
{ key:"hullet", value:"hole "},
{ key:"hjørnet", value:"corner "},
{ key:"rundt", value:" around, approximately "},
{ key:"fryseren", value:"freezer "},
{ key:"taket", value:"roof, ceiling "},
{ key:"loftet", value:"attic "},
{ key:"etasje", value:"floor "},
{ key:"duken", value:"tablecloth "},
{ key:"setter", value:"put,place "},
{ key:"legger", value:"put, lay "},
{ key:"putter", value:"put"},
{ key:"kjelleren", value:"basement "},
{ key:"speilet", value:"mirror "},
{ key:"støv", value:"dust"},
{ key:"blyanten", value:"pencil "},
{ key:"fjernkontroll", value:"remote control "},
{ key:"dørmatte", value:"doormat "},
{ key:"definitiv/definitivt ", value:" definitely "},
{ key:"stikke", value:" run off "},
{ key:"før", value:" before "},
{ key:"vanen", value:"habit "},
{ key:"uvane", value:"bad habbit "},
{ key:"slem/slemt", value:" mean, unkind "},
{ key:"daglig/daglige", value:" daily "},
{ key:"stoppskiltet", value:"stop sign "},
{ key:"sparkesykler", value:"scooters"},
{ key:"sakte", value:" slowly"},
{ key:"saktere", value:" slower"},
{ key:"håret", value:"hair "},
{ key:"lav/lavt/lave", value:" low, short "},
{ key:"lavere", value:" lower"},
{ key:"laveste", value:" lowest"},
{ key:"beinet", value:"leg, bone "},
{ key:"dressen", value:"suit "},
{ key:"fraket", value:"coat "},
{ key:"banen", value:"field "},
{ key:"fotballbannen", value:"football soccer field"},
{ key:"løken", value:"onion "},
{ key:"soppen", value:"mushroom "},
{ key:"søndagsåpne", value:" open on sunday"},
{ key:"hamburgeren", value:"hamburger "},
{ key:"rulleskøytene", value:"rollerskates "},
{ key:"loppemarkedet", value:"flea market "},
{ key:"heisen", value:"elevator "},
{ key:"under", value:" under"},
{ key:"undertøyet", value:"underwear "},
{ key:"skjegget", value:"beard "},
{ key:"smykker", value:" jewlery"},
{ key:"halskjedet", value:"necklace "},
{ key:"blond", value:" blond haired"},
{ key:"lommen", value:"pocket "},
{ key:"lommeboken", value:"wallet "},
{ key:"passer", value:"fit "},
{ key:"passer på", value:"look after "},
{ key:"trang", value:" tight, narrow "},
{ key:"knapp", value:"button "},
{ key:"perfekt", value:" perfectly"},
{ key:"verktøykasse", value:" worktoolbox"},
{ key:"bildet", value:"photo, picture "},
{ key:"båten", value:"boat "},
{ key:"naturen", value:"nature "},
{ key:"innsjøen", value:"lake "},
{ key:"temperaturen", value:"temperature "},
{ key:"graden", value:"degree "},
{ key:"celsius", value:" celcius"},
{ key:"gjennom", value:" through"},
{ key:"leiebilen", value:"rental car"},
{ key:"forlater", value:"leave "},
{ key:"forlot", value:" left"},
{ key:"klokken", value:"watch "},
{ key:"vekkerklokken", value:"alarm clock"},
{ key:"rutinen", value:"routine "},
{ key:"dusjer", value:"shower"},
{ key:"tannen", value:"tooth "},
{ key:"tenner", value:" teeth"},
{ key:"syltetøyet", value:"jam"},
{ key:"pusser", value:"brush "},
{ key:"gården", value:"farm "},
{ key:"bladet", value:"magazine "},
{ key:"selskapet", value:"company "},
{ key:"fuglen", value:"bird "},
{ key:"elgen", value:"moose, elk "},
{ key:"anden", value:"duck "},
{ key:"hesten", value:"horse "},
{ key:"bjørnen", value:"bear "},
{ key:"edderkoppen", value:"spider "},
{ key:"lukter", value:"smell "},
{ key:"musen", value:"mouse "},
{ key:"ulven", value:"wolf "},
{ key:"veterinæren", value:"veterinary "},
{ key:"båndet", value:"leash "},
{ key:"måte", value:" way, manner "},
{ key:"agurktid", value:" slow news season "},
{ key:"folk", value:" people"},
{ key:"sist", value:" e fundit, last, last time "},
{ key:"mistet", value:" lost "},
{ key:"ligger", value:"lie "},
{ key:"ligget", value:" lay, was lying "},
{ key:"lå", value:" qe, lay "},
{ key:"anelse", value:" idea "},
{ key:"nede", value:" downstairs "},
{ key:"oppe", value:" upstairs "},
{ key:"luren", value:"nap "},
{ key:"overalt", value:" everywhere"},
{ key:"skuffen", value:"drawer "},
{ key:"medisinen", value:"medicine "},
{ key:"heltid", value:" full time "},
{ key:"mastergraden", value:"masters degree "},
{ key:"lingvistikk", value:" linguistics"},
{ key:"informatikk", value:" computer science"},
{ key:"kurset", value:"course "},
{ key:"forelesningen", value:"lecture "},
{ key:"karakteren", value:"grade "},
{ key:"høyskolen", value:"university, shkolle e larte "},
{ key:"badekaret", value:"bathtub "},
{ key:"håndkleet", value:"towel "},
{ key:"studentbolingen ", value:"student dorm "},
{ key:"semesteret", value:"semester "},
{ key:"rockekonserten", value:"rock consert "},
{ key:"fyren", value:"guy"},
{ key:"trommer", value:"drums"},
{ key:"musiker/musikerne ", value:"musicians"},
{ key:"en scene/scenen ", value:"stage "},
{ key:"en smarttelefone/smarttelefonen/smarttelefoner ", value:"smart phone"},
{ key:"hvem som", value:" who "},
{ key:"favorittseng", value:" favorite song"},
{ key:"et album/albumet ", value:"album"},
{ key:"låner/å låne", value:"lend"},
{ key:"gråter", value:"cry "},
{ key:"hjemmefra", value:" from home"},
{ key:"tvillinger", value:" twins"},
{ key:"tvillingbroren", value:"twin brother "},
{ key:"hel", value:" whole "},
{ key:"forfatteren", value:"author "},
{ key:"bygger", value:"build "},
{ key:"bygde", value:" built "},
{ key:"bygget", value:" built "},
{ key:"et bygg/bygget ", value:"building"},
{ key:"en robot/roboten ", value:"robot"},
{ key:"matte", value:" math"},
{ key:"matte", value:" rug"},
{ key:"drømmejobb", value:" dream job"},
{ key:"ingeniør", value:" engineer "},
{ key:"pilot", value:" pilot "},
{ key:"et helikopter/helikopteret ", value:"helicopter"},
{ key:"komiker", value:" comedians"},
{ key:"et landskape/landskapet ", value:"landscape"},
{ key:"fotografene", value:"photographers"},
{ key:"en premie/premien/premier ", value:"prize"},
{ key:"tjener", value:"earn"},
{ key:"et miljøe/miljøet ", value:"environment"},
{ key:"filmstjernen", value:"movie star"},
{ key:"slipsene", value:"ties"},
{ key:"velger", value:"choose"},
{ key:"et belte/beltet//beltene ", value:"belt"},
{ key:"et gull/gullet", value:"gold"},
{ key:"morsdagen", value:"mothersday"},
{ key:"skinn", value:" leather"},
{ key:"farsdagen", value:"fathersday"},
{ key:"et slips/slipset/slipsene ", value:"tie"},
{ key:"velger", value:"choose"},
{ key:"salg", value:" sales "},
{ key:"prøverom", value:" fitting rooms"},
{ key:"en plakate/plakaten ", value:"poster"},
{ key:"khemmekontoret", value:"home office"},
{ key:"en kjøper/kjøperen ", value:"buyer"},
{ key:"shortsen", value:"shorts"},
{ key:"lommepenger", value:" pocket money"},
{ key:"en skjerm/skjermen ", value:"screen "},
{ key:"bør", value:" should"},
{ key:"en nakke/nakken ", value:"neck"},
{ key:"stiv", value:" stiff"},
{ key:"en nese/nesen", value:"nose "},
{ key:"et øre/øret/ører/ørene ", value:"ear"},
{ key:"blek/bleke", value:" pale "},
{ key:"regelmessig", value:" regularly"},
{ key:"alkoholen", value:"alcohol"},
{ key:"svinekjøtt", value:" pork"},
{ key:"storfekjøtt", value:" beef"},
{ key:"en tunge/tungen/tunger ", value:"tounge"},
{ key:"en kropp/kroppen ", value:"body"},
{ key:"en helse/helsen ", value:"health"},
{ key:"en munn/munnen", value:"mouth"},
{ key:"peker/å peke", value:"point "},
{ key:"pekte", value:" pointed"},
{ key:"tærne", value:"toes "},
{ key:"et ansikt/ansiktet/ansikter/ansiktene ", value:"face"},
{ key:"planer", value:" plans"},
{ key:"frekk/frekke", value:" rude "},
{ key:"i det hele tatt ", value:" at all"},
{ key:"løser/å løse", value:"solve"},
{ key:"biologi", value:" biology"},
{ key:"geografi", value:" geography"},
{ key:"en minne/minnen/minner/minnene ", value:"memory"},
{ key:"forleden", value:"other "},
{ key:"et kart/kartet", value:"map"},
{ key:"innflyttingsfest", value:" house warming party"},
{ key:"overfor", value:" accross"},
{ key:"spesielt", value:" especially"},
{ key:"kvadratmeter", value:" square meters"},
{ key:"en pølse/pølsen/pølser/pølsene ", value:"sausage"},
{ key:"et ektepar/ekteparet ", value:"married couple"},
{ key:"et potetgulle/potetgullet ", value:"chips"},
{ key:"sprøtt", value:" crispy"},
{ key:"sprø", value:" crispy"},
{ key:"sprøest", value:" crispiest"},
{ key:"en slange/slangen ", value:"snake"},
{ key:"slangeskinn", value:" snakeskin"},
{ key:"en dagbok/dagboken", value:"diary"},
{ key:"løser/å løse", value:"solve"},
{ key:"løste", value:" solved"},
{ key:"puslespill", value:" puzzles"},
{ key:"i fjor", value:" last year "},
{ key:"kunst", value:" art"},
{ key:"et fag/faget", value:"subject "},
{ key:"innflyttingsfesten ", value:"housewarming party"},
{ key:"en ektefelle/ektefellen ", value:"spouse"},
{ key:"komfyren", value:"stove"},
{ key:"katedralen", value:"cathedral"},
{ key:"vinmonopolet", value:"wine monopoly"},
{ key:"utsikten", value:"view"},
{ key:"uvanlige", value:" unusual"},
{ key:"opp til meg", value:" upme"},
{ key:"sender/å sende", value:"send "},
{ key:"sendte", value:" sent"},
{ key:"mater/å mate", value:"feed"},
{ key:"et postkort/postkortet ", value:"postcard"},
{ key:"tjeneste", value:" favor"},
{ key:"et dekk/dekket/dekkene ", value:"tire"},
{ key:"flat/flatt", value:" flat "},
{ key:"skifter/å skifte ", value:"change "},
{ key:"skiftet", value:" changed"},
{ key:"en mekaniker/mekanikeren/mekanikerne ", value:"mechanic"},
{ key:"et brev/brevet/brev/brevene ", value:"letter"},
{ key:"et konvolutt/konvolutten ", value:"envelope"},
{ key:"en frimerke/frimerken/frimerker ", value:"stamp"},
{ key:"skyld", value:" sake "},
{ key:"en boks/boksen", value:"can"},
{ key:"ølboksen", value:"beer can"},
{ key:"takker", value:"thank"},
{ key:"takket", value:" thanked"},
{ key:"sender ut", value:" send out"},
{ key:"setebelter", value:" seatbelts"},
{ key:"en sektretær/sekretæren ", value:"secretary"},
{ key:"kopiere", value:"copy"},
{ key:"dokumenter", value:" documents"},
{ key:"konferanse", value:" conference "},
{ key:"reparerer/å reparere ", value:"repair"},
{ key:"en maskine/maskinen ", value:"machine"},
{ key:"en prest/presten/prester ", value:"priest"},
{ key:"håndverker", value:" tranesperson"},
{ key:"fritiden", value:"free time "},
{ key:"sjelden", value:" seldom, rarely"},
{ key:"bussjåføren", value:"bus driver"},
{ key:"sommerjobb", value:" summer job"},
{ key:"telefonselger", value:" telemarketer"},
{ key:"brannmennene", value:"firemen"},
{ key:"en rørlegger/rørleggeren//rørleggerne ", value:"plumber"},
{ key:"en elektriker/elektrikeren/elektrikere/elektrikerne ", value:"electrician"},
{ key:"overtid", value:" overtime"},
{ key:"arbeidsklærne", value:" workclothes"},
{ key:"arbeidsmiløet", value:"working environment"},
{ key:"india", value:" india"},
{ key:"gresk/greske", value:" greek "},
{ key:"en forrett/forretten ", value:"appetizer"},
{ key:"en hovedrette/hovedretten", value:"main course"},
{ key:"leveringstjenesten ", value:"delivery service"},
{ key:"tilbyr", value:"offer "},
{ key:"tilbød", value:" offered"},
{ key:"en tallerken/tallerkenen/tallerkener/tallerkenene ", value:"plate"},
{ key:"en bønne/bønnen/bønner/bønnene ", value:"bean"},
{ key:"kaffebønner", value:" coffee beans"},
{ key:"et måltid/måltiden ", value:"meal"},
{ key:"serverer", value:"serve"},
{ key:"sur", value:" sour"},
{ key:"laks", value:" salmon"},
{ key:"husnummeret", value:"house number"},
{ key:"postnummeret", value:"zip code"},
{ key:"smør", value:" butter"},
{ key:"hvitløk", value:" garlik"},
{ key:"oljen", value:"oil "},
{ key:"et tips/tips", value:"tip "},
{ key:"småpenger", value:" change"},
{ key:"eddik", value:" vinegar"},
{ key:"riseddik", value:" rice vinegar"},
{ key:"en rykte/rykten/rykter/ryktene ", value:"rumor"},
{ key:"sladrer/å sladre", value:"gossip"},
{ key:"lyver/å lyve", value:"lie"},
{ key:"løy", value:" lied "},
{ key:"spøkelset", value:" ghost "},
{ key:"hjemsøkt", value:" haunted"},
{ key:"ond/onde", value:" evil"},
{ key:"nysgjerrig", value:" curious "},
{ key:"en heks/heksen/hekser/heksene ", value:" witch"},
{ key:"et uhyre/uhyret/uhyrer/uhyrene ", value:"monster"},
{ key:"føler/å føle", value:"feel"},
{ key:"følelsen", value:" feeling "},
];
