name: Update Version of index.html

on: 
  push: 
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version file
        run: |
          echo "const version = $(git rev-parse --short HEAD);" > version.js
          echo "console.log('Version:', version);" >> version.js

      - name: List dir content
        run: ls -al

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
