name: Update version.js

on: 
  push: 
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate word list
        run: echo 'const pairs = [' > wl.js ; awk "/#/,/##/" norsk.txt | grep "\-\-" | sed 's/^\([^\-\-]*\)\-\-\([^:]*\).*/{ key:"\1", value:"\2"},/g; s/   *//g; s/ the //g; s/ to //g' >> wl.js ; echo '];' >> wl.js


      - name: Update version file
        run: |
          echo "const version = '$(git rev-parse --short HEAD)';" > version.js
          echo "console.log('Version:', version);" >> version.js

      - name: List dir content
        run: ls -al

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
